package com.rdc.kingsa.input.persistence.beans;

import java.util.Date;

public class Approval {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPROVAL.ID
     *
     * @mbggenerated Sat Sep 29 22:44:50 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPROVAL.TYPE
     *
     * @mbggenerated Sat Sep 29 22:44:50 CST 2018
     */
    private Short type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPROVAL.STATUE
     *
     * @mbggenerated Sat Sep 29 22:44:50 CST 2018
     */
    private Short statue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPROVAL.LAST_TIME
     *
     * @mbggenerated Sat Sep 29 22:44:50 CST 2018
     */
    private Date lastTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPROVAL.ID
     *
     * @return the value of APPROVAL.ID
     *
     * @mbggenerated Sat Sep 29 22:44:50 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPROVAL.ID
     *
     * @param id the value for APPROVAL.ID
     *
     * @mbggenerated Sat Sep 29 22:44:50 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPROVAL.TYPE
     *
     * @return the value of APPROVAL.TYPE
     *
     * @mbggenerated Sat Sep 29 22:44:50 CST 2018
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPROVAL.TYPE
     *
     * @param type the value for APPROVAL.TYPE
     *
     * @mbggenerated Sat Sep 29 22:44:50 CST 2018
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPROVAL.STATUE
     *
     * @return the value of APPROVAL.STATUE
     *
     * @mbggenerated Sat Sep 29 22:44:50 CST 2018
     */
    public Short getStatue() {
        return statue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPROVAL.STATUE
     *
     * @param statue the value for APPROVAL.STATUE
     *
     * @mbggenerated Sat Sep 29 22:44:50 CST 2018
     */
    public void setStatue(Short statue) {
        this.statue = statue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPROVAL.LAST_TIME
     *
     * @return the value of APPROVAL.LAST_TIME
     *
     * @mbggenerated Sat Sep 29 22:44:50 CST 2018
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPROVAL.LAST_TIME
     *
     * @param lastTime the value for APPROVAL.LAST_TIME
     *
     * @mbggenerated Sat Sep 29 22:44:50 CST 2018
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }
}