package com.rdc.kingsa.input.persistence.beans;

import java.util.Date;

public class CatchRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATCH_RECORD.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATCH_RECORD.CATCH_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String catchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATCH_RECORD.CATCH_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Date catchTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATCH_RECORD.SECTION_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String sectionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATCH_RECORD.SAMPLING_POINT
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String samplingPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATCH_RECORD.SERIAL_NUMBER
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Long serialNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATCH_RECORD.BIO_ORDER
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String bioOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATCH_RECORD.FAMILY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String family;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATCH_RECORD.SUB_FAMILY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String subFamily;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATCH_RECORD.GENUS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String genus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATCH_RECORD.SPECIES_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String speciesName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATCH_RECORD.OVERALL_LENGTH
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Integer overallLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATCH_RECORD.BODY_LENGTH
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Integer bodyLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATCH_RECORD.WEIGHT
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATCH_RECORD.EMPTY_WEIGHT
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double emptyWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATCH_RECORD.GONAD
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String gonad;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATCH_RECORD.FEEDING_HABITS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String feedingHabits;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATCH_RECORD.PHYSICAL_AGE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String physicalAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATCH_RECORD.OTHER_THINGS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String otherThings;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATCH_RECORD.CREATE_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATCH_RECORD.MODIFY_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATCH_RECORD.REMARKS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATCH_RECORD.ID
     *
     * @return the value of CATCH_RECORD.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATCH_RECORD.ID
     *
     * @param id the value for CATCH_RECORD.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATCH_RECORD.CATCH_ID
     *
     * @return the value of CATCH_RECORD.CATCH_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getCatchId() {
        return catchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATCH_RECORD.CATCH_ID
     *
     * @param catchId the value for CATCH_RECORD.CATCH_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setCatchId(String catchId) {
        this.catchId = catchId == null ? null : catchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATCH_RECORD.CATCH_TIME
     *
     * @return the value of CATCH_RECORD.CATCH_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Date getCatchTime() {
        return catchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATCH_RECORD.CATCH_TIME
     *
     * @param catchTime the value for CATCH_RECORD.CATCH_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setCatchTime(Date catchTime) {
        this.catchTime = catchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATCH_RECORD.SECTION_ID
     *
     * @return the value of CATCH_RECORD.SECTION_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getSectionId() {
        return sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATCH_RECORD.SECTION_ID
     *
     * @param sectionId the value for CATCH_RECORD.SECTION_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setSectionId(String sectionId) {
        this.sectionId = sectionId == null ? null : sectionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATCH_RECORD.SAMPLING_POINT
     *
     * @return the value of CATCH_RECORD.SAMPLING_POINT
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getSamplingPoint() {
        return samplingPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATCH_RECORD.SAMPLING_POINT
     *
     * @param samplingPoint the value for CATCH_RECORD.SAMPLING_POINT
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setSamplingPoint(String samplingPoint) {
        this.samplingPoint = samplingPoint == null ? null : samplingPoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATCH_RECORD.SERIAL_NUMBER
     *
     * @return the value of CATCH_RECORD.SERIAL_NUMBER
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Long getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATCH_RECORD.SERIAL_NUMBER
     *
     * @param serialNumber the value for CATCH_RECORD.SERIAL_NUMBER
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setSerialNumber(Long serialNumber) {
        this.serialNumber = serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATCH_RECORD.BIO_ORDER
     *
     * @return the value of CATCH_RECORD.BIO_ORDER
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getBioOrder() {
        return bioOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATCH_RECORD.BIO_ORDER
     *
     * @param bioOrder the value for CATCH_RECORD.BIO_ORDER
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setBioOrder(String bioOrder) {
        this.bioOrder = bioOrder == null ? null : bioOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATCH_RECORD.FAMILY
     *
     * @return the value of CATCH_RECORD.FAMILY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getFamily() {
        return family;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATCH_RECORD.FAMILY
     *
     * @param family the value for CATCH_RECORD.FAMILY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setFamily(String family) {
        this.family = family == null ? null : family.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATCH_RECORD.SUB_FAMILY
     *
     * @return the value of CATCH_RECORD.SUB_FAMILY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getSubFamily() {
        return subFamily;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATCH_RECORD.SUB_FAMILY
     *
     * @param subFamily the value for CATCH_RECORD.SUB_FAMILY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setSubFamily(String subFamily) {
        this.subFamily = subFamily == null ? null : subFamily.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATCH_RECORD.GENUS
     *
     * @return the value of CATCH_RECORD.GENUS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getGenus() {
        return genus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATCH_RECORD.GENUS
     *
     * @param genus the value for CATCH_RECORD.GENUS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setGenus(String genus) {
        this.genus = genus == null ? null : genus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATCH_RECORD.SPECIES_NAME
     *
     * @return the value of CATCH_RECORD.SPECIES_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getSpeciesName() {
        return speciesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATCH_RECORD.SPECIES_NAME
     *
     * @param speciesName the value for CATCH_RECORD.SPECIES_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setSpeciesName(String speciesName) {
        this.speciesName = speciesName == null ? null : speciesName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATCH_RECORD.OVERALL_LENGTH
     *
     * @return the value of CATCH_RECORD.OVERALL_LENGTH
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Integer getOverallLength() {
        return overallLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATCH_RECORD.OVERALL_LENGTH
     *
     * @param overallLength the value for CATCH_RECORD.OVERALL_LENGTH
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setOverallLength(Integer overallLength) {
        this.overallLength = overallLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATCH_RECORD.BODY_LENGTH
     *
     * @return the value of CATCH_RECORD.BODY_LENGTH
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Integer getBodyLength() {
        return bodyLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATCH_RECORD.BODY_LENGTH
     *
     * @param bodyLength the value for CATCH_RECORD.BODY_LENGTH
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setBodyLength(Integer bodyLength) {
        this.bodyLength = bodyLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATCH_RECORD.WEIGHT
     *
     * @return the value of CATCH_RECORD.WEIGHT
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATCH_RECORD.WEIGHT
     *
     * @param weight the value for CATCH_RECORD.WEIGHT
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATCH_RECORD.EMPTY_WEIGHT
     *
     * @return the value of CATCH_RECORD.EMPTY_WEIGHT
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getEmptyWeight() {
        return emptyWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATCH_RECORD.EMPTY_WEIGHT
     *
     * @param emptyWeight the value for CATCH_RECORD.EMPTY_WEIGHT
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setEmptyWeight(Double emptyWeight) {
        this.emptyWeight = emptyWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATCH_RECORD.GONAD
     *
     * @return the value of CATCH_RECORD.GONAD
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getGonad() {
        return gonad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATCH_RECORD.GONAD
     *
     * @param gonad the value for CATCH_RECORD.GONAD
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setGonad(String gonad) {
        this.gonad = gonad == null ? null : gonad.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATCH_RECORD.FEEDING_HABITS
     *
     * @return the value of CATCH_RECORD.FEEDING_HABITS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getFeedingHabits() {
        return feedingHabits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATCH_RECORD.FEEDING_HABITS
     *
     * @param feedingHabits the value for CATCH_RECORD.FEEDING_HABITS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setFeedingHabits(String feedingHabits) {
        this.feedingHabits = feedingHabits == null ? null : feedingHabits.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATCH_RECORD.PHYSICAL_AGE
     *
     * @return the value of CATCH_RECORD.PHYSICAL_AGE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getPhysicalAge() {
        return physicalAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATCH_RECORD.PHYSICAL_AGE
     *
     * @param physicalAge the value for CATCH_RECORD.PHYSICAL_AGE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setPhysicalAge(String physicalAge) {
        this.physicalAge = physicalAge == null ? null : physicalAge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATCH_RECORD.OTHER_THINGS
     *
     * @return the value of CATCH_RECORD.OTHER_THINGS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getOtherThings() {
        return otherThings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATCH_RECORD.OTHER_THINGS
     *
     * @param otherThings the value for CATCH_RECORD.OTHER_THINGS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setOtherThings(String otherThings) {
        this.otherThings = otherThings == null ? null : otherThings.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATCH_RECORD.CREATE_TIME
     *
     * @return the value of CATCH_RECORD.CREATE_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATCH_RECORD.CREATE_TIME
     *
     * @param createTime the value for CATCH_RECORD.CREATE_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATCH_RECORD.MODIFY_TIME
     *
     * @return the value of CATCH_RECORD.MODIFY_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATCH_RECORD.MODIFY_TIME
     *
     * @param modifyTime the value for CATCH_RECORD.MODIFY_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATCH_RECORD.REMARKS
     *
     * @return the value of CATCH_RECORD.REMARKS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATCH_RECORD.REMARKS
     *
     * @param remarks the value for CATCH_RECORD.REMARKS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}