package com.rdc.kingsa.input.persistence.beans;

import java.math.BigDecimal;
import java.util.Date;

public class ClimateValueRain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIMATE_VALUE_RAIN.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIMATE_VALUE_RAIN.H1
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private BigDecimal h1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIMATE_VALUE_RAIN.H2
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private BigDecimal h2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIMATE_VALUE_RAIN.H3
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private BigDecimal h3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIMATE_VALUE_RAIN.H4
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private BigDecimal h4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIMATE_VALUE_RAIN.H5
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private BigDecimal h5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIMATE_VALUE_RAIN.H6
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private BigDecimal h6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIMATE_VALUE_RAIN.H7
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private BigDecimal h7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIMATE_VALUE_RAIN.H8
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private BigDecimal h8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIMATE_VALUE_RAIN.H9
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private BigDecimal h9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIMATE_VALUE_RAIN.H10
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private BigDecimal h10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIMATE_VALUE_RAIN.H11
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private BigDecimal h11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIMATE_VALUE_RAIN.H12
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private BigDecimal h12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIMATE_VALUE_RAIN.H13
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private BigDecimal h13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIMATE_VALUE_RAIN.H14
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private BigDecimal h14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIMATE_VALUE_RAIN.H15
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private BigDecimal h15;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIMATE_VALUE_RAIN.H16
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private BigDecimal h16;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIMATE_VALUE_RAIN.H17
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private BigDecimal h17;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIMATE_VALUE_RAIN.H18
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private BigDecimal h18;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIMATE_VALUE_RAIN.H19
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private BigDecimal h19;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIMATE_VALUE_RAIN.H20
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private BigDecimal h20;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIMATE_VALUE_RAIN.H21
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private BigDecimal h21;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIMATE_VALUE_RAIN.H22
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private BigDecimal h22;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIMATE_VALUE_RAIN.H23
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private BigDecimal h23;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIMATE_VALUE_RAIN.H24
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private BigDecimal h24;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIMATE_VALUE_RAIN.MONITOR_DATE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Date monitorDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIMATE_VALUE_RAIN.RECORD_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIMATE_VALUE_RAIN.TOTAL
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private BigDecimal total;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIMATE_VALUE_RAIN.ID
     *
     * @return the value of CLIMATE_VALUE_RAIN.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIMATE_VALUE_RAIN.ID
     *
     * @param id the value for CLIMATE_VALUE_RAIN.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIMATE_VALUE_RAIN.H1
     *
     * @return the value of CLIMATE_VALUE_RAIN.H1
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public BigDecimal getH1() {
        return h1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIMATE_VALUE_RAIN.H1
     *
     * @param h1 the value for CLIMATE_VALUE_RAIN.H1
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setH1(BigDecimal h1) {
        this.h1 = h1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIMATE_VALUE_RAIN.H2
     *
     * @return the value of CLIMATE_VALUE_RAIN.H2
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public BigDecimal getH2() {
        return h2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIMATE_VALUE_RAIN.H2
     *
     * @param h2 the value for CLIMATE_VALUE_RAIN.H2
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setH2(BigDecimal h2) {
        this.h2 = h2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIMATE_VALUE_RAIN.H3
     *
     * @return the value of CLIMATE_VALUE_RAIN.H3
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public BigDecimal getH3() {
        return h3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIMATE_VALUE_RAIN.H3
     *
     * @param h3 the value for CLIMATE_VALUE_RAIN.H3
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setH3(BigDecimal h3) {
        this.h3 = h3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIMATE_VALUE_RAIN.H4
     *
     * @return the value of CLIMATE_VALUE_RAIN.H4
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public BigDecimal getH4() {
        return h4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIMATE_VALUE_RAIN.H4
     *
     * @param h4 the value for CLIMATE_VALUE_RAIN.H4
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setH4(BigDecimal h4) {
        this.h4 = h4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIMATE_VALUE_RAIN.H5
     *
     * @return the value of CLIMATE_VALUE_RAIN.H5
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public BigDecimal getH5() {
        return h5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIMATE_VALUE_RAIN.H5
     *
     * @param h5 the value for CLIMATE_VALUE_RAIN.H5
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setH5(BigDecimal h5) {
        this.h5 = h5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIMATE_VALUE_RAIN.H6
     *
     * @return the value of CLIMATE_VALUE_RAIN.H6
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public BigDecimal getH6() {
        return h6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIMATE_VALUE_RAIN.H6
     *
     * @param h6 the value for CLIMATE_VALUE_RAIN.H6
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setH6(BigDecimal h6) {
        this.h6 = h6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIMATE_VALUE_RAIN.H7
     *
     * @return the value of CLIMATE_VALUE_RAIN.H7
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public BigDecimal getH7() {
        return h7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIMATE_VALUE_RAIN.H7
     *
     * @param h7 the value for CLIMATE_VALUE_RAIN.H7
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setH7(BigDecimal h7) {
        this.h7 = h7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIMATE_VALUE_RAIN.H8
     *
     * @return the value of CLIMATE_VALUE_RAIN.H8
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public BigDecimal getH8() {
        return h8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIMATE_VALUE_RAIN.H8
     *
     * @param h8 the value for CLIMATE_VALUE_RAIN.H8
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setH8(BigDecimal h8) {
        this.h8 = h8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIMATE_VALUE_RAIN.H9
     *
     * @return the value of CLIMATE_VALUE_RAIN.H9
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public BigDecimal getH9() {
        return h9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIMATE_VALUE_RAIN.H9
     *
     * @param h9 the value for CLIMATE_VALUE_RAIN.H9
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setH9(BigDecimal h9) {
        this.h9 = h9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIMATE_VALUE_RAIN.H10
     *
     * @return the value of CLIMATE_VALUE_RAIN.H10
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public BigDecimal getH10() {
        return h10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIMATE_VALUE_RAIN.H10
     *
     * @param h10 the value for CLIMATE_VALUE_RAIN.H10
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setH10(BigDecimal h10) {
        this.h10 = h10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIMATE_VALUE_RAIN.H11
     *
     * @return the value of CLIMATE_VALUE_RAIN.H11
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public BigDecimal getH11() {
        return h11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIMATE_VALUE_RAIN.H11
     *
     * @param h11 the value for CLIMATE_VALUE_RAIN.H11
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setH11(BigDecimal h11) {
        this.h11 = h11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIMATE_VALUE_RAIN.H12
     *
     * @return the value of CLIMATE_VALUE_RAIN.H12
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public BigDecimal getH12() {
        return h12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIMATE_VALUE_RAIN.H12
     *
     * @param h12 the value for CLIMATE_VALUE_RAIN.H12
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setH12(BigDecimal h12) {
        this.h12 = h12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIMATE_VALUE_RAIN.H13
     *
     * @return the value of CLIMATE_VALUE_RAIN.H13
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public BigDecimal getH13() {
        return h13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIMATE_VALUE_RAIN.H13
     *
     * @param h13 the value for CLIMATE_VALUE_RAIN.H13
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setH13(BigDecimal h13) {
        this.h13 = h13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIMATE_VALUE_RAIN.H14
     *
     * @return the value of CLIMATE_VALUE_RAIN.H14
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public BigDecimal getH14() {
        return h14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIMATE_VALUE_RAIN.H14
     *
     * @param h14 the value for CLIMATE_VALUE_RAIN.H14
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setH14(BigDecimal h14) {
        this.h14 = h14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIMATE_VALUE_RAIN.H15
     *
     * @return the value of CLIMATE_VALUE_RAIN.H15
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public BigDecimal getH15() {
        return h15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIMATE_VALUE_RAIN.H15
     *
     * @param h15 the value for CLIMATE_VALUE_RAIN.H15
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setH15(BigDecimal h15) {
        this.h15 = h15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIMATE_VALUE_RAIN.H16
     *
     * @return the value of CLIMATE_VALUE_RAIN.H16
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public BigDecimal getH16() {
        return h16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIMATE_VALUE_RAIN.H16
     *
     * @param h16 the value for CLIMATE_VALUE_RAIN.H16
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setH16(BigDecimal h16) {
        this.h16 = h16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIMATE_VALUE_RAIN.H17
     *
     * @return the value of CLIMATE_VALUE_RAIN.H17
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public BigDecimal getH17() {
        return h17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIMATE_VALUE_RAIN.H17
     *
     * @param h17 the value for CLIMATE_VALUE_RAIN.H17
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setH17(BigDecimal h17) {
        this.h17 = h17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIMATE_VALUE_RAIN.H18
     *
     * @return the value of CLIMATE_VALUE_RAIN.H18
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public BigDecimal getH18() {
        return h18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIMATE_VALUE_RAIN.H18
     *
     * @param h18 the value for CLIMATE_VALUE_RAIN.H18
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setH18(BigDecimal h18) {
        this.h18 = h18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIMATE_VALUE_RAIN.H19
     *
     * @return the value of CLIMATE_VALUE_RAIN.H19
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public BigDecimal getH19() {
        return h19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIMATE_VALUE_RAIN.H19
     *
     * @param h19 the value for CLIMATE_VALUE_RAIN.H19
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setH19(BigDecimal h19) {
        this.h19 = h19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIMATE_VALUE_RAIN.H20
     *
     * @return the value of CLIMATE_VALUE_RAIN.H20
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public BigDecimal getH20() {
        return h20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIMATE_VALUE_RAIN.H20
     *
     * @param h20 the value for CLIMATE_VALUE_RAIN.H20
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setH20(BigDecimal h20) {
        this.h20 = h20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIMATE_VALUE_RAIN.H21
     *
     * @return the value of CLIMATE_VALUE_RAIN.H21
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public BigDecimal getH21() {
        return h21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIMATE_VALUE_RAIN.H21
     *
     * @param h21 the value for CLIMATE_VALUE_RAIN.H21
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setH21(BigDecimal h21) {
        this.h21 = h21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIMATE_VALUE_RAIN.H22
     *
     * @return the value of CLIMATE_VALUE_RAIN.H22
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public BigDecimal getH22() {
        return h22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIMATE_VALUE_RAIN.H22
     *
     * @param h22 the value for CLIMATE_VALUE_RAIN.H22
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setH22(BigDecimal h22) {
        this.h22 = h22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIMATE_VALUE_RAIN.H23
     *
     * @return the value of CLIMATE_VALUE_RAIN.H23
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public BigDecimal getH23() {
        return h23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIMATE_VALUE_RAIN.H23
     *
     * @param h23 the value for CLIMATE_VALUE_RAIN.H23
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setH23(BigDecimal h23) {
        this.h23 = h23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIMATE_VALUE_RAIN.H24
     *
     * @return the value of CLIMATE_VALUE_RAIN.H24
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public BigDecimal getH24() {
        return h24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIMATE_VALUE_RAIN.H24
     *
     * @param h24 the value for CLIMATE_VALUE_RAIN.H24
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setH24(BigDecimal h24) {
        this.h24 = h24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIMATE_VALUE_RAIN.MONITOR_DATE
     *
     * @return the value of CLIMATE_VALUE_RAIN.MONITOR_DATE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Date getMonitorDate() {
        return monitorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIMATE_VALUE_RAIN.MONITOR_DATE
     *
     * @param monitorDate the value for CLIMATE_VALUE_RAIN.MONITOR_DATE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setMonitorDate(Date monitorDate) {
        this.monitorDate = monitorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIMATE_VALUE_RAIN.RECORD_ID
     *
     * @return the value of CLIMATE_VALUE_RAIN.RECORD_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIMATE_VALUE_RAIN.RECORD_ID
     *
     * @param recordId the value for CLIMATE_VALUE_RAIN.RECORD_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setRecordId(String recordId) {
        this.recordId = recordId == null ? null : recordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIMATE_VALUE_RAIN.TOTAL
     *
     * @return the value of CLIMATE_VALUE_RAIN.TOTAL
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIMATE_VALUE_RAIN.TOTAL
     *
     * @param total the value for CLIMATE_VALUE_RAIN.TOTAL
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
}