package com.rdc.kingsa.input.persistence.beans;

public class Department {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPARTMENT.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPARTMENT.DEPARTMENT_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String departmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPARTMENT.ADMINISTRATIVE_DUTIES
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String administrativeDuties;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPARTMENT.DIRECTOR
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String director;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPARTMENT.NUMBER_OF_PERSON
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Integer numberOfPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPARTMENT.TELNUM
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String telnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPARTMENT.ADDRESS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPARTMENT.DESCRIPTION
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPARTMENT.LEVEL
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Integer level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPARTMENT.ID
     *
     * @return the value of DEPARTMENT.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPARTMENT.ID
     *
     * @param id the value for DEPARTMENT.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPARTMENT.DEPARTMENT_NAME
     *
     * @return the value of DEPARTMENT.DEPARTMENT_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPARTMENT.DEPARTMENT_NAME
     *
     * @param departmentName the value for DEPARTMENT.DEPARTMENT_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPARTMENT.ADMINISTRATIVE_DUTIES
     *
     * @return the value of DEPARTMENT.ADMINISTRATIVE_DUTIES
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getAdministrativeDuties() {
        return administrativeDuties;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPARTMENT.ADMINISTRATIVE_DUTIES
     *
     * @param administrativeDuties the value for DEPARTMENT.ADMINISTRATIVE_DUTIES
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setAdministrativeDuties(String administrativeDuties) {
        this.administrativeDuties = administrativeDuties == null ? null : administrativeDuties.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPARTMENT.DIRECTOR
     *
     * @return the value of DEPARTMENT.DIRECTOR
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getDirector() {
        return director;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPARTMENT.DIRECTOR
     *
     * @param director the value for DEPARTMENT.DIRECTOR
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setDirector(String director) {
        this.director = director == null ? null : director.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPARTMENT.NUMBER_OF_PERSON
     *
     * @return the value of DEPARTMENT.NUMBER_OF_PERSON
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Integer getNumberOfPerson() {
        return numberOfPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPARTMENT.NUMBER_OF_PERSON
     *
     * @param numberOfPerson the value for DEPARTMENT.NUMBER_OF_PERSON
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setNumberOfPerson(Integer numberOfPerson) {
        this.numberOfPerson = numberOfPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPARTMENT.TELNUM
     *
     * @return the value of DEPARTMENT.TELNUM
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getTelnum() {
        return telnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPARTMENT.TELNUM
     *
     * @param telnum the value for DEPARTMENT.TELNUM
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setTelnum(String telnum) {
        this.telnum = telnum == null ? null : telnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPARTMENT.ADDRESS
     *
     * @return the value of DEPARTMENT.ADDRESS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPARTMENT.ADDRESS
     *
     * @param address the value for DEPARTMENT.ADDRESS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPARTMENT.DESCRIPTION
     *
     * @return the value of DEPARTMENT.DESCRIPTION
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPARTMENT.DESCRIPTION
     *
     * @param description the value for DEPARTMENT.DESCRIPTION
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPARTMENT.LEVEL
     *
     * @return the value of DEPARTMENT.LEVEL
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPARTMENT.LEVEL
     *
     * @param level the value for DEPARTMENT.LEVEL
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setLevel(Integer level) {
        this.level = level;
    }
}