package com.rdc.kingsa.input.persistence.beans;

public class DocFileTag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_FILE_TAG.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_FILE_TAG.FILE_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_FILE_TAG.TAG_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String tagId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_FILE_TAG.ID
     *
     * @return the value of DOC_FILE_TAG.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_FILE_TAG.ID
     *
     * @param id the value for DOC_FILE_TAG.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_FILE_TAG.FILE_ID
     *
     * @return the value of DOC_FILE_TAG.FILE_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_FILE_TAG.FILE_ID
     *
     * @param fileId the value for DOC_FILE_TAG.FILE_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_FILE_TAG.TAG_ID
     *
     * @return the value of DOC_FILE_TAG.TAG_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_FILE_TAG.TAG_ID
     *
     * @param tagId the value for DOC_FILE_TAG.TAG_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setTagId(String tagId) {
        this.tagId = tagId == null ? null : tagId.trim();
    }
}