package com.rdc.kingsa.input.persistence.beans;

public class DocFolderTag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_FOLDER_TAG.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_FOLDER_TAG.FOLDER_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String folderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_FOLDER_TAG.TAG_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String tagId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_FOLDER_TAG.ID
     *
     * @return the value of DOC_FOLDER_TAG.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_FOLDER_TAG.ID
     *
     * @param id the value for DOC_FOLDER_TAG.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_FOLDER_TAG.FOLDER_ID
     *
     * @return the value of DOC_FOLDER_TAG.FOLDER_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getFolderId() {
        return folderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_FOLDER_TAG.FOLDER_ID
     *
     * @param folderId the value for DOC_FOLDER_TAG.FOLDER_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setFolderId(String folderId) {
        this.folderId = folderId == null ? null : folderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_FOLDER_TAG.TAG_ID
     *
     * @return the value of DOC_FOLDER_TAG.TAG_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_FOLDER_TAG.TAG_ID
     *
     * @param tagId the value for DOC_FOLDER_TAG.TAG_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setTagId(String tagId) {
        this.tagId = tagId == null ? null : tagId.trim();
    }
}