package com.rdc.kingsa.input.persistence.beans;

import java.util.Date;

public class DocFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_FILE.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_FILE.FILE_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_FILE.URL
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_FILE.UPLOADER_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String uploaderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_FILE.UPLOAD_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Date uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_FILE.REMARKS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_FILE.MODIFY_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_FILE.UPLOAD_DEPT_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String uploadDeptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_FILE.UPLOADER_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String uploaderName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_FILE.UPLOAD_DEPT_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String uploadDeptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_FILE.EXTENSION_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String extensionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_FILE.FILE_PINYIN
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String filePinyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_FILE.FILE_PY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String filePy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_FILE.FOLDER_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String folderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_FILE.UPLOADER_PINYIN
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String uploaderPinyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_FILE.UPLOADER_PY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String uploaderPy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_FILE.ID
     *
     * @return the value of DOC_FILE.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_FILE.ID
     *
     * @param id the value for DOC_FILE.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_FILE.FILE_NAME
     *
     * @return the value of DOC_FILE.FILE_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_FILE.FILE_NAME
     *
     * @param fileName the value for DOC_FILE.FILE_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_FILE.URL
     *
     * @return the value of DOC_FILE.URL
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_FILE.URL
     *
     * @param url the value for DOC_FILE.URL
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_FILE.UPLOADER_ID
     *
     * @return the value of DOC_FILE.UPLOADER_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getUploaderId() {
        return uploaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_FILE.UPLOADER_ID
     *
     * @param uploaderId the value for DOC_FILE.UPLOADER_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setUploaderId(String uploaderId) {
        this.uploaderId = uploaderId == null ? null : uploaderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_FILE.UPLOAD_TIME
     *
     * @return the value of DOC_FILE.UPLOAD_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_FILE.UPLOAD_TIME
     *
     * @param uploadTime the value for DOC_FILE.UPLOAD_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_FILE.REMARKS
     *
     * @return the value of DOC_FILE.REMARKS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_FILE.REMARKS
     *
     * @param remarks the value for DOC_FILE.REMARKS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_FILE.MODIFY_TIME
     *
     * @return the value of DOC_FILE.MODIFY_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_FILE.MODIFY_TIME
     *
     * @param modifyTime the value for DOC_FILE.MODIFY_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_FILE.UPLOAD_DEPT_ID
     *
     * @return the value of DOC_FILE.UPLOAD_DEPT_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getUploadDeptId() {
        return uploadDeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_FILE.UPLOAD_DEPT_ID
     *
     * @param uploadDeptId the value for DOC_FILE.UPLOAD_DEPT_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setUploadDeptId(String uploadDeptId) {
        this.uploadDeptId = uploadDeptId == null ? null : uploadDeptId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_FILE.UPLOADER_NAME
     *
     * @return the value of DOC_FILE.UPLOADER_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getUploaderName() {
        return uploaderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_FILE.UPLOADER_NAME
     *
     * @param uploaderName the value for DOC_FILE.UPLOADER_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setUploaderName(String uploaderName) {
        this.uploaderName = uploaderName == null ? null : uploaderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_FILE.UPLOAD_DEPT_NAME
     *
     * @return the value of DOC_FILE.UPLOAD_DEPT_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getUploadDeptName() {
        return uploadDeptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_FILE.UPLOAD_DEPT_NAME
     *
     * @param uploadDeptName the value for DOC_FILE.UPLOAD_DEPT_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setUploadDeptName(String uploadDeptName) {
        this.uploadDeptName = uploadDeptName == null ? null : uploadDeptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_FILE.EXTENSION_NAME
     *
     * @return the value of DOC_FILE.EXTENSION_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getExtensionName() {
        return extensionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_FILE.EXTENSION_NAME
     *
     * @param extensionName the value for DOC_FILE.EXTENSION_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setExtensionName(String extensionName) {
        this.extensionName = extensionName == null ? null : extensionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_FILE.FILE_PINYIN
     *
     * @return the value of DOC_FILE.FILE_PINYIN
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getFilePinyin() {
        return filePinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_FILE.FILE_PINYIN
     *
     * @param filePinyin the value for DOC_FILE.FILE_PINYIN
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setFilePinyin(String filePinyin) {
        this.filePinyin = filePinyin == null ? null : filePinyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_FILE.FILE_PY
     *
     * @return the value of DOC_FILE.FILE_PY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getFilePy() {
        return filePy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_FILE.FILE_PY
     *
     * @param filePy the value for DOC_FILE.FILE_PY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setFilePy(String filePy) {
        this.filePy = filePy == null ? null : filePy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_FILE.FOLDER_ID
     *
     * @return the value of DOC_FILE.FOLDER_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getFolderId() {
        return folderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_FILE.FOLDER_ID
     *
     * @param folderId the value for DOC_FILE.FOLDER_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setFolderId(String folderId) {
        this.folderId = folderId == null ? null : folderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_FILE.UPLOADER_PINYIN
     *
     * @return the value of DOC_FILE.UPLOADER_PINYIN
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getUploaderPinyin() {
        return uploaderPinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_FILE.UPLOADER_PINYIN
     *
     * @param uploaderPinyin the value for DOC_FILE.UPLOADER_PINYIN
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setUploaderPinyin(String uploaderPinyin) {
        this.uploaderPinyin = uploaderPinyin == null ? null : uploaderPinyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_FILE.UPLOADER_PY
     *
     * @return the value of DOC_FILE.UPLOADER_PY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getUploaderPy() {
        return uploaderPy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_FILE.UPLOADER_PY
     *
     * @param uploaderPy the value for DOC_FILE.UPLOADER_PY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setUploaderPy(String uploaderPy) {
        this.uploaderPy = uploaderPy == null ? null : uploaderPy.trim();
    }
}