package com.rdc.kingsa.input.persistence.beans;

public class DocTag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_TAG.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_TAG.TAG_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String tagName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_TAG.TAG_PINYIN
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String tagPinyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_TAG.TAG_PY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String tagPy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_TAG.ID
     *
     * @return the value of DOC_TAG.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_TAG.ID
     *
     * @param id the value for DOC_TAG.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_TAG.TAG_NAME
     *
     * @return the value of DOC_TAG.TAG_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_TAG.TAG_NAME
     *
     * @param tagName the value for DOC_TAG.TAG_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setTagName(String tagName) {
        this.tagName = tagName == null ? null : tagName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_TAG.TAG_PINYIN
     *
     * @return the value of DOC_TAG.TAG_PINYIN
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getTagPinyin() {
        return tagPinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_TAG.TAG_PINYIN
     *
     * @param tagPinyin the value for DOC_TAG.TAG_PINYIN
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setTagPinyin(String tagPinyin) {
        this.tagPinyin = tagPinyin == null ? null : tagPinyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_TAG.TAG_PY
     *
     * @return the value of DOC_TAG.TAG_PY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getTagPy() {
        return tagPy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_TAG.TAG_PY
     *
     * @param tagPy the value for DOC_TAG.TAG_PY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setTagPy(String tagPy) {
        this.tagPy = tagPy == null ? null : tagPy.trim();
    }
}