package com.rdc.kingsa.input.persistence.beans;

import java.util.Date;

public class DoEstimateStandard {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DO_ESTIMATE_STANDARD.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DO_ESTIMATE_STANDARD.SERIAL_NUM
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Short serialNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DO_ESTIMATE_STANDARD.EVALUATE_ITEM
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String evaluateItem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DO_ESTIMATE_STANDARD.TYPE_I_UL
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double typeIUl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DO_ESTIMATE_STANDARD.TYPE_I_UL_SOC
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Short typeIUlSoc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DO_ESTIMATE_STANDARD.TYPE_I_LL
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double typeILl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DO_ESTIMATE_STANDARD.TYPE_I_LL_SOC
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Short typeILlSoc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DO_ESTIMATE_STANDARD.TYPE_II_UL
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double typeIiUl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DO_ESTIMATE_STANDARD.TYPE_II_UL_SOC
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Short typeIiUlSoc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DO_ESTIMATE_STANDARD.TYPE_II_LL
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double typeIiLl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DO_ESTIMATE_STANDARD.TYPE_II_LL_SOC
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Short typeIiLlSoc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DO_ESTIMATE_STANDARD.TYPE_III_UL
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double typeIiiUl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DO_ESTIMATE_STANDARD.TYPE_III_UL_SOC
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Short typeIiiUlSoc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DO_ESTIMATE_STANDARD.TYPE_III_LL
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double typeIiiLl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DO_ESTIMATE_STANDARD.TYPE_III_LL_SOC
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Short typeIiiLlSoc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DO_ESTIMATE_STANDARD.CREATE_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DO_ESTIMATE_STANDARD.MODIFY_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DO_ESTIMATE_STANDARD.REMARKS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DO_ESTIMATE_STANDARD.ID
     *
     * @return the value of DO_ESTIMATE_STANDARD.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DO_ESTIMATE_STANDARD.ID
     *
     * @param id the value for DO_ESTIMATE_STANDARD.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DO_ESTIMATE_STANDARD.SERIAL_NUM
     *
     * @return the value of DO_ESTIMATE_STANDARD.SERIAL_NUM
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Short getSerialNum() {
        return serialNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DO_ESTIMATE_STANDARD.SERIAL_NUM
     *
     * @param serialNum the value for DO_ESTIMATE_STANDARD.SERIAL_NUM
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setSerialNum(Short serialNum) {
        this.serialNum = serialNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DO_ESTIMATE_STANDARD.EVALUATE_ITEM
     *
     * @return the value of DO_ESTIMATE_STANDARD.EVALUATE_ITEM
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getEvaluateItem() {
        return evaluateItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DO_ESTIMATE_STANDARD.EVALUATE_ITEM
     *
     * @param evaluateItem the value for DO_ESTIMATE_STANDARD.EVALUATE_ITEM
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setEvaluateItem(String evaluateItem) {
        this.evaluateItem = evaluateItem == null ? null : evaluateItem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DO_ESTIMATE_STANDARD.TYPE_I_UL
     *
     * @return the value of DO_ESTIMATE_STANDARD.TYPE_I_UL
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getTypeIUl() {
        return typeIUl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DO_ESTIMATE_STANDARD.TYPE_I_UL
     *
     * @param typeIUl the value for DO_ESTIMATE_STANDARD.TYPE_I_UL
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setTypeIUl(Double typeIUl) {
        this.typeIUl = typeIUl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DO_ESTIMATE_STANDARD.TYPE_I_UL_SOC
     *
     * @return the value of DO_ESTIMATE_STANDARD.TYPE_I_UL_SOC
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Short getTypeIUlSoc() {
        return typeIUlSoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DO_ESTIMATE_STANDARD.TYPE_I_UL_SOC
     *
     * @param typeIUlSoc the value for DO_ESTIMATE_STANDARD.TYPE_I_UL_SOC
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setTypeIUlSoc(Short typeIUlSoc) {
        this.typeIUlSoc = typeIUlSoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DO_ESTIMATE_STANDARD.TYPE_I_LL
     *
     * @return the value of DO_ESTIMATE_STANDARD.TYPE_I_LL
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getTypeILl() {
        return typeILl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DO_ESTIMATE_STANDARD.TYPE_I_LL
     *
     * @param typeILl the value for DO_ESTIMATE_STANDARD.TYPE_I_LL
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setTypeILl(Double typeILl) {
        this.typeILl = typeILl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DO_ESTIMATE_STANDARD.TYPE_I_LL_SOC
     *
     * @return the value of DO_ESTIMATE_STANDARD.TYPE_I_LL_SOC
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Short getTypeILlSoc() {
        return typeILlSoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DO_ESTIMATE_STANDARD.TYPE_I_LL_SOC
     *
     * @param typeILlSoc the value for DO_ESTIMATE_STANDARD.TYPE_I_LL_SOC
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setTypeILlSoc(Short typeILlSoc) {
        this.typeILlSoc = typeILlSoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DO_ESTIMATE_STANDARD.TYPE_II_UL
     *
     * @return the value of DO_ESTIMATE_STANDARD.TYPE_II_UL
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getTypeIiUl() {
        return typeIiUl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DO_ESTIMATE_STANDARD.TYPE_II_UL
     *
     * @param typeIiUl the value for DO_ESTIMATE_STANDARD.TYPE_II_UL
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setTypeIiUl(Double typeIiUl) {
        this.typeIiUl = typeIiUl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DO_ESTIMATE_STANDARD.TYPE_II_UL_SOC
     *
     * @return the value of DO_ESTIMATE_STANDARD.TYPE_II_UL_SOC
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Short getTypeIiUlSoc() {
        return typeIiUlSoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DO_ESTIMATE_STANDARD.TYPE_II_UL_SOC
     *
     * @param typeIiUlSoc the value for DO_ESTIMATE_STANDARD.TYPE_II_UL_SOC
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setTypeIiUlSoc(Short typeIiUlSoc) {
        this.typeIiUlSoc = typeIiUlSoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DO_ESTIMATE_STANDARD.TYPE_II_LL
     *
     * @return the value of DO_ESTIMATE_STANDARD.TYPE_II_LL
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getTypeIiLl() {
        return typeIiLl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DO_ESTIMATE_STANDARD.TYPE_II_LL
     *
     * @param typeIiLl the value for DO_ESTIMATE_STANDARD.TYPE_II_LL
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setTypeIiLl(Double typeIiLl) {
        this.typeIiLl = typeIiLl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DO_ESTIMATE_STANDARD.TYPE_II_LL_SOC
     *
     * @return the value of DO_ESTIMATE_STANDARD.TYPE_II_LL_SOC
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Short getTypeIiLlSoc() {
        return typeIiLlSoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DO_ESTIMATE_STANDARD.TYPE_II_LL_SOC
     *
     * @param typeIiLlSoc the value for DO_ESTIMATE_STANDARD.TYPE_II_LL_SOC
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setTypeIiLlSoc(Short typeIiLlSoc) {
        this.typeIiLlSoc = typeIiLlSoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DO_ESTIMATE_STANDARD.TYPE_III_UL
     *
     * @return the value of DO_ESTIMATE_STANDARD.TYPE_III_UL
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getTypeIiiUl() {
        return typeIiiUl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DO_ESTIMATE_STANDARD.TYPE_III_UL
     *
     * @param typeIiiUl the value for DO_ESTIMATE_STANDARD.TYPE_III_UL
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setTypeIiiUl(Double typeIiiUl) {
        this.typeIiiUl = typeIiiUl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DO_ESTIMATE_STANDARD.TYPE_III_UL_SOC
     *
     * @return the value of DO_ESTIMATE_STANDARD.TYPE_III_UL_SOC
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Short getTypeIiiUlSoc() {
        return typeIiiUlSoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DO_ESTIMATE_STANDARD.TYPE_III_UL_SOC
     *
     * @param typeIiiUlSoc the value for DO_ESTIMATE_STANDARD.TYPE_III_UL_SOC
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setTypeIiiUlSoc(Short typeIiiUlSoc) {
        this.typeIiiUlSoc = typeIiiUlSoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DO_ESTIMATE_STANDARD.TYPE_III_LL
     *
     * @return the value of DO_ESTIMATE_STANDARD.TYPE_III_LL
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getTypeIiiLl() {
        return typeIiiLl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DO_ESTIMATE_STANDARD.TYPE_III_LL
     *
     * @param typeIiiLl the value for DO_ESTIMATE_STANDARD.TYPE_III_LL
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setTypeIiiLl(Double typeIiiLl) {
        this.typeIiiLl = typeIiiLl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DO_ESTIMATE_STANDARD.TYPE_III_LL_SOC
     *
     * @return the value of DO_ESTIMATE_STANDARD.TYPE_III_LL_SOC
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Short getTypeIiiLlSoc() {
        return typeIiiLlSoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DO_ESTIMATE_STANDARD.TYPE_III_LL_SOC
     *
     * @param typeIiiLlSoc the value for DO_ESTIMATE_STANDARD.TYPE_III_LL_SOC
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setTypeIiiLlSoc(Short typeIiiLlSoc) {
        this.typeIiiLlSoc = typeIiiLlSoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DO_ESTIMATE_STANDARD.CREATE_TIME
     *
     * @return the value of DO_ESTIMATE_STANDARD.CREATE_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DO_ESTIMATE_STANDARD.CREATE_TIME
     *
     * @param createTime the value for DO_ESTIMATE_STANDARD.CREATE_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DO_ESTIMATE_STANDARD.MODIFY_TIME
     *
     * @return the value of DO_ESTIMATE_STANDARD.MODIFY_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DO_ESTIMATE_STANDARD.MODIFY_TIME
     *
     * @param modifyTime the value for DO_ESTIMATE_STANDARD.MODIFY_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DO_ESTIMATE_STANDARD.REMARKS
     *
     * @return the value of DO_ESTIMATE_STANDARD.REMARKS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DO_ESTIMATE_STANDARD.REMARKS
     *
     * @param remarks the value for DO_ESTIMATE_STANDARD.REMARKS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}