package com.rdc.kingsa.input.persistence.beans;

public class Fault {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FAULT.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FAULT.FAULT_NUM
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String faultNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FAULT.DAM_DISTANCE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double damDistance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FAULT.ESTUARY_DISTANCE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double estuaryDistance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FAULT.RIVER_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String riverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FAULT.LEFT_BANK_X
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double leftBankX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FAULT.LEFT_BANK_Y
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double leftBankY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FAULT.RIGHT_BANK_X
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double rightBankX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FAULT.RIGHT_BANK_Y
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double rightBankY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FAULT.LEFT_BANK_ELEVATION
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double leftBankElevation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FAULT.RIGHT_BANK_ELEVATION
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double rightBankElevation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FAULT.LOCATION_RESERVOIR
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String locationReservoir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FAULT.TYPE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FAULT.ID
     *
     * @return the value of FAULT.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FAULT.ID
     *
     * @param id the value for FAULT.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FAULT.FAULT_NUM
     *
     * @return the value of FAULT.FAULT_NUM
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getFaultNum() {
        return faultNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FAULT.FAULT_NUM
     *
     * @param faultNum the value for FAULT.FAULT_NUM
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setFaultNum(String faultNum) {
        this.faultNum = faultNum == null ? null : faultNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FAULT.DAM_DISTANCE
     *
     * @return the value of FAULT.DAM_DISTANCE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getDamDistance() {
        return damDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FAULT.DAM_DISTANCE
     *
     * @param damDistance the value for FAULT.DAM_DISTANCE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setDamDistance(Double damDistance) {
        this.damDistance = damDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FAULT.ESTUARY_DISTANCE
     *
     * @return the value of FAULT.ESTUARY_DISTANCE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getEstuaryDistance() {
        return estuaryDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FAULT.ESTUARY_DISTANCE
     *
     * @param estuaryDistance the value for FAULT.ESTUARY_DISTANCE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setEstuaryDistance(Double estuaryDistance) {
        this.estuaryDistance = estuaryDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FAULT.RIVER_NAME
     *
     * @return the value of FAULT.RIVER_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getRiverName() {
        return riverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FAULT.RIVER_NAME
     *
     * @param riverName the value for FAULT.RIVER_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setRiverName(String riverName) {
        this.riverName = riverName == null ? null : riverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FAULT.LEFT_BANK_X
     *
     * @return the value of FAULT.LEFT_BANK_X
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getLeftBankX() {
        return leftBankX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FAULT.LEFT_BANK_X
     *
     * @param leftBankX the value for FAULT.LEFT_BANK_X
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setLeftBankX(Double leftBankX) {
        this.leftBankX = leftBankX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FAULT.LEFT_BANK_Y
     *
     * @return the value of FAULT.LEFT_BANK_Y
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getLeftBankY() {
        return leftBankY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FAULT.LEFT_BANK_Y
     *
     * @param leftBankY the value for FAULT.LEFT_BANK_Y
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setLeftBankY(Double leftBankY) {
        this.leftBankY = leftBankY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FAULT.RIGHT_BANK_X
     *
     * @return the value of FAULT.RIGHT_BANK_X
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getRightBankX() {
        return rightBankX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FAULT.RIGHT_BANK_X
     *
     * @param rightBankX the value for FAULT.RIGHT_BANK_X
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setRightBankX(Double rightBankX) {
        this.rightBankX = rightBankX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FAULT.RIGHT_BANK_Y
     *
     * @return the value of FAULT.RIGHT_BANK_Y
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getRightBankY() {
        return rightBankY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FAULT.RIGHT_BANK_Y
     *
     * @param rightBankY the value for FAULT.RIGHT_BANK_Y
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setRightBankY(Double rightBankY) {
        this.rightBankY = rightBankY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FAULT.LEFT_BANK_ELEVATION
     *
     * @return the value of FAULT.LEFT_BANK_ELEVATION
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getLeftBankElevation() {
        return leftBankElevation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FAULT.LEFT_BANK_ELEVATION
     *
     * @param leftBankElevation the value for FAULT.LEFT_BANK_ELEVATION
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setLeftBankElevation(Double leftBankElevation) {
        this.leftBankElevation = leftBankElevation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FAULT.RIGHT_BANK_ELEVATION
     *
     * @return the value of FAULT.RIGHT_BANK_ELEVATION
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getRightBankElevation() {
        return rightBankElevation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FAULT.RIGHT_BANK_ELEVATION
     *
     * @param rightBankElevation the value for FAULT.RIGHT_BANK_ELEVATION
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setRightBankElevation(Double rightBankElevation) {
        this.rightBankElevation = rightBankElevation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FAULT.LOCATION_RESERVOIR
     *
     * @return the value of FAULT.LOCATION_RESERVOIR
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getLocationReservoir() {
        return locationReservoir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FAULT.LOCATION_RESERVOIR
     *
     * @param locationReservoir the value for FAULT.LOCATION_RESERVOIR
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setLocationReservoir(String locationReservoir) {
        this.locationReservoir = locationReservoir == null ? null : locationReservoir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FAULT.TYPE
     *
     * @return the value of FAULT.TYPE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FAULT.TYPE
     *
     * @param type the value for FAULT.TYPE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}