package com.rdc.kingsa.input.persistence.beans;

import java.util.Date;

public class FdaMonitorPhoto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FDA_MONITOR_PHOTO.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FDA_MONITOR_PHOTO.MONITOR_RECORD_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String monitorRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FDA_MONITOR_PHOTO.FILE_URL
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String fileUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FDA_MONITOR_PHOTO.FILE_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FDA_MONITOR_PHOTO.FILE_CATEGORY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String fileCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FDA_MONITOR_PHOTO.CREATE_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FDA_MONITOR_PHOTO.MODIFY_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FDA_MONITOR_PHOTO.REMARKS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FDA_MONITOR_PHOTO.ID
     *
     * @return the value of FDA_MONITOR_PHOTO.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FDA_MONITOR_PHOTO.ID
     *
     * @param id the value for FDA_MONITOR_PHOTO.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FDA_MONITOR_PHOTO.MONITOR_RECORD_ID
     *
     * @return the value of FDA_MONITOR_PHOTO.MONITOR_RECORD_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getMonitorRecordId() {
        return monitorRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FDA_MONITOR_PHOTO.MONITOR_RECORD_ID
     *
     * @param monitorRecordId the value for FDA_MONITOR_PHOTO.MONITOR_RECORD_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setMonitorRecordId(String monitorRecordId) {
        this.monitorRecordId = monitorRecordId == null ? null : monitorRecordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FDA_MONITOR_PHOTO.FILE_URL
     *
     * @return the value of FDA_MONITOR_PHOTO.FILE_URL
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FDA_MONITOR_PHOTO.FILE_URL
     *
     * @param fileUrl the value for FDA_MONITOR_PHOTO.FILE_URL
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl == null ? null : fileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FDA_MONITOR_PHOTO.FILE_NAME
     *
     * @return the value of FDA_MONITOR_PHOTO.FILE_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FDA_MONITOR_PHOTO.FILE_NAME
     *
     * @param fileName the value for FDA_MONITOR_PHOTO.FILE_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FDA_MONITOR_PHOTO.FILE_CATEGORY
     *
     * @return the value of FDA_MONITOR_PHOTO.FILE_CATEGORY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getFileCategory() {
        return fileCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FDA_MONITOR_PHOTO.FILE_CATEGORY
     *
     * @param fileCategory the value for FDA_MONITOR_PHOTO.FILE_CATEGORY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setFileCategory(String fileCategory) {
        this.fileCategory = fileCategory == null ? null : fileCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FDA_MONITOR_PHOTO.CREATE_TIME
     *
     * @return the value of FDA_MONITOR_PHOTO.CREATE_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FDA_MONITOR_PHOTO.CREATE_TIME
     *
     * @param createTime the value for FDA_MONITOR_PHOTO.CREATE_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FDA_MONITOR_PHOTO.MODIFY_TIME
     *
     * @return the value of FDA_MONITOR_PHOTO.MODIFY_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FDA_MONITOR_PHOTO.MODIFY_TIME
     *
     * @param modifyTime the value for FDA_MONITOR_PHOTO.MODIFY_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FDA_MONITOR_PHOTO.REMARKS
     *
     * @return the value of FDA_MONITOR_PHOTO.REMARKS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FDA_MONITOR_PHOTO.REMARKS
     *
     * @param remarks the value for FDA_MONITOR_PHOTO.REMARKS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}