package com.rdc.kingsa.input.persistence.beans;

import java.math.BigDecimal;
import java.util.Date;

public class FdaMonitorRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FDA_MONITOR_RECORD.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FDA_MONITOR_RECORD.START_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FDA_MONITOR_RECORD.INPUT_FLOW_MIN
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private BigDecimal inputFlowMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FDA_MONITOR_RECORD.OUTPUT_FLOW_MIN
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private BigDecimal outputFlowMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FDA_MONITOR_RECORD.OPEN_MODE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String openMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FDA_MONITOR_RECORD.UPSTREAM_WATERLINE_MIN
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private BigDecimal upstreamWaterlineMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FDA_MONITOR_RECORD.DOWNSTREAM_WATERLINE_MIN
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private BigDecimal downstreamWaterlineMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FDA_MONITOR_RECORD.CREATE_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FDA_MONITOR_RECORD.MODIFY_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FDA_MONITOR_RECORD.REMARKS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FDA_MONITOR_RECORD.END_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FDA_MONITOR_RECORD.MONITOR_RECORD_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String monitorRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FDA_MONITOR_RECORD.INPUT_FLOW_MAX
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private BigDecimal inputFlowMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FDA_MONITOR_RECORD.OUTPUT_FLOW_MAX
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private BigDecimal outputFlowMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FDA_MONITOR_RECORD.UPSTREAM_WATERLINE_MAX
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private BigDecimal upstreamWaterlineMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FDA_MONITOR_RECORD.DOWNSTREAM_WATERLINE_MAX
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private BigDecimal downstreamWaterlineMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FDA_MONITOR_RECORD.MONITOR_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Date monitorTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FDA_MONITOR_RECORD.MONITOR_AGENT
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String monitorAgent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FDA_MONITOR_RECORD.REPORTER
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String reporter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FDA_MONITOR_RECORD.FDA_SHAPE_DESCRIPTION
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String fdaShapeDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FDA_MONITOR_RECORD.FDA_CONCLUSION
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String fdaConclusion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FDA_MONITOR_RECORD.STATION_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String stationId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FDA_MONITOR_RECORD.ID
     *
     * @return the value of FDA_MONITOR_RECORD.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FDA_MONITOR_RECORD.ID
     *
     * @param id the value for FDA_MONITOR_RECORD.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FDA_MONITOR_RECORD.START_TIME
     *
     * @return the value of FDA_MONITOR_RECORD.START_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FDA_MONITOR_RECORD.START_TIME
     *
     * @param startTime the value for FDA_MONITOR_RECORD.START_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FDA_MONITOR_RECORD.INPUT_FLOW_MIN
     *
     * @return the value of FDA_MONITOR_RECORD.INPUT_FLOW_MIN
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public BigDecimal getInputFlowMin() {
        return inputFlowMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FDA_MONITOR_RECORD.INPUT_FLOW_MIN
     *
     * @param inputFlowMin the value for FDA_MONITOR_RECORD.INPUT_FLOW_MIN
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setInputFlowMin(BigDecimal inputFlowMin) {
        this.inputFlowMin = inputFlowMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FDA_MONITOR_RECORD.OUTPUT_FLOW_MIN
     *
     * @return the value of FDA_MONITOR_RECORD.OUTPUT_FLOW_MIN
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public BigDecimal getOutputFlowMin() {
        return outputFlowMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FDA_MONITOR_RECORD.OUTPUT_FLOW_MIN
     *
     * @param outputFlowMin the value for FDA_MONITOR_RECORD.OUTPUT_FLOW_MIN
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setOutputFlowMin(BigDecimal outputFlowMin) {
        this.outputFlowMin = outputFlowMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FDA_MONITOR_RECORD.OPEN_MODE
     *
     * @return the value of FDA_MONITOR_RECORD.OPEN_MODE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getOpenMode() {
        return openMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FDA_MONITOR_RECORD.OPEN_MODE
     *
     * @param openMode the value for FDA_MONITOR_RECORD.OPEN_MODE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setOpenMode(String openMode) {
        this.openMode = openMode == null ? null : openMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FDA_MONITOR_RECORD.UPSTREAM_WATERLINE_MIN
     *
     * @return the value of FDA_MONITOR_RECORD.UPSTREAM_WATERLINE_MIN
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public BigDecimal getUpstreamWaterlineMin() {
        return upstreamWaterlineMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FDA_MONITOR_RECORD.UPSTREAM_WATERLINE_MIN
     *
     * @param upstreamWaterlineMin the value for FDA_MONITOR_RECORD.UPSTREAM_WATERLINE_MIN
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setUpstreamWaterlineMin(BigDecimal upstreamWaterlineMin) {
        this.upstreamWaterlineMin = upstreamWaterlineMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FDA_MONITOR_RECORD.DOWNSTREAM_WATERLINE_MIN
     *
     * @return the value of FDA_MONITOR_RECORD.DOWNSTREAM_WATERLINE_MIN
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public BigDecimal getDownstreamWaterlineMin() {
        return downstreamWaterlineMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FDA_MONITOR_RECORD.DOWNSTREAM_WATERLINE_MIN
     *
     * @param downstreamWaterlineMin the value for FDA_MONITOR_RECORD.DOWNSTREAM_WATERLINE_MIN
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setDownstreamWaterlineMin(BigDecimal downstreamWaterlineMin) {
        this.downstreamWaterlineMin = downstreamWaterlineMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FDA_MONITOR_RECORD.CREATE_TIME
     *
     * @return the value of FDA_MONITOR_RECORD.CREATE_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FDA_MONITOR_RECORD.CREATE_TIME
     *
     * @param createTime the value for FDA_MONITOR_RECORD.CREATE_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FDA_MONITOR_RECORD.MODIFY_TIME
     *
     * @return the value of FDA_MONITOR_RECORD.MODIFY_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FDA_MONITOR_RECORD.MODIFY_TIME
     *
     * @param modifyTime the value for FDA_MONITOR_RECORD.MODIFY_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FDA_MONITOR_RECORD.REMARKS
     *
     * @return the value of FDA_MONITOR_RECORD.REMARKS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FDA_MONITOR_RECORD.REMARKS
     *
     * @param remarks the value for FDA_MONITOR_RECORD.REMARKS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FDA_MONITOR_RECORD.END_TIME
     *
     * @return the value of FDA_MONITOR_RECORD.END_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FDA_MONITOR_RECORD.END_TIME
     *
     * @param endTime the value for FDA_MONITOR_RECORD.END_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FDA_MONITOR_RECORD.MONITOR_RECORD_ID
     *
     * @return the value of FDA_MONITOR_RECORD.MONITOR_RECORD_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getMonitorRecordId() {
        return monitorRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FDA_MONITOR_RECORD.MONITOR_RECORD_ID
     *
     * @param monitorRecordId the value for FDA_MONITOR_RECORD.MONITOR_RECORD_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setMonitorRecordId(String monitorRecordId) {
        this.monitorRecordId = monitorRecordId == null ? null : monitorRecordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FDA_MONITOR_RECORD.INPUT_FLOW_MAX
     *
     * @return the value of FDA_MONITOR_RECORD.INPUT_FLOW_MAX
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public BigDecimal getInputFlowMax() {
        return inputFlowMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FDA_MONITOR_RECORD.INPUT_FLOW_MAX
     *
     * @param inputFlowMax the value for FDA_MONITOR_RECORD.INPUT_FLOW_MAX
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setInputFlowMax(BigDecimal inputFlowMax) {
        this.inputFlowMax = inputFlowMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FDA_MONITOR_RECORD.OUTPUT_FLOW_MAX
     *
     * @return the value of FDA_MONITOR_RECORD.OUTPUT_FLOW_MAX
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public BigDecimal getOutputFlowMax() {
        return outputFlowMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FDA_MONITOR_RECORD.OUTPUT_FLOW_MAX
     *
     * @param outputFlowMax the value for FDA_MONITOR_RECORD.OUTPUT_FLOW_MAX
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setOutputFlowMax(BigDecimal outputFlowMax) {
        this.outputFlowMax = outputFlowMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FDA_MONITOR_RECORD.UPSTREAM_WATERLINE_MAX
     *
     * @return the value of FDA_MONITOR_RECORD.UPSTREAM_WATERLINE_MAX
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public BigDecimal getUpstreamWaterlineMax() {
        return upstreamWaterlineMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FDA_MONITOR_RECORD.UPSTREAM_WATERLINE_MAX
     *
     * @param upstreamWaterlineMax the value for FDA_MONITOR_RECORD.UPSTREAM_WATERLINE_MAX
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setUpstreamWaterlineMax(BigDecimal upstreamWaterlineMax) {
        this.upstreamWaterlineMax = upstreamWaterlineMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FDA_MONITOR_RECORD.DOWNSTREAM_WATERLINE_MAX
     *
     * @return the value of FDA_MONITOR_RECORD.DOWNSTREAM_WATERLINE_MAX
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public BigDecimal getDownstreamWaterlineMax() {
        return downstreamWaterlineMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FDA_MONITOR_RECORD.DOWNSTREAM_WATERLINE_MAX
     *
     * @param downstreamWaterlineMax the value for FDA_MONITOR_RECORD.DOWNSTREAM_WATERLINE_MAX
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setDownstreamWaterlineMax(BigDecimal downstreamWaterlineMax) {
        this.downstreamWaterlineMax = downstreamWaterlineMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FDA_MONITOR_RECORD.MONITOR_TIME
     *
     * @return the value of FDA_MONITOR_RECORD.MONITOR_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Date getMonitorTime() {
        return monitorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FDA_MONITOR_RECORD.MONITOR_TIME
     *
     * @param monitorTime the value for FDA_MONITOR_RECORD.MONITOR_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setMonitorTime(Date monitorTime) {
        this.monitorTime = monitorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FDA_MONITOR_RECORD.MONITOR_AGENT
     *
     * @return the value of FDA_MONITOR_RECORD.MONITOR_AGENT
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getMonitorAgent() {
        return monitorAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FDA_MONITOR_RECORD.MONITOR_AGENT
     *
     * @param monitorAgent the value for FDA_MONITOR_RECORD.MONITOR_AGENT
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setMonitorAgent(String monitorAgent) {
        this.monitorAgent = monitorAgent == null ? null : monitorAgent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FDA_MONITOR_RECORD.REPORTER
     *
     * @return the value of FDA_MONITOR_RECORD.REPORTER
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getReporter() {
        return reporter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FDA_MONITOR_RECORD.REPORTER
     *
     * @param reporter the value for FDA_MONITOR_RECORD.REPORTER
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setReporter(String reporter) {
        this.reporter = reporter == null ? null : reporter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FDA_MONITOR_RECORD.FDA_SHAPE_DESCRIPTION
     *
     * @return the value of FDA_MONITOR_RECORD.FDA_SHAPE_DESCRIPTION
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getFdaShapeDescription() {
        return fdaShapeDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FDA_MONITOR_RECORD.FDA_SHAPE_DESCRIPTION
     *
     * @param fdaShapeDescription the value for FDA_MONITOR_RECORD.FDA_SHAPE_DESCRIPTION
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setFdaShapeDescription(String fdaShapeDescription) {
        this.fdaShapeDescription = fdaShapeDescription == null ? null : fdaShapeDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FDA_MONITOR_RECORD.FDA_CONCLUSION
     *
     * @return the value of FDA_MONITOR_RECORD.FDA_CONCLUSION
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getFdaConclusion() {
        return fdaConclusion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FDA_MONITOR_RECORD.FDA_CONCLUSION
     *
     * @param fdaConclusion the value for FDA_MONITOR_RECORD.FDA_CONCLUSION
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setFdaConclusion(String fdaConclusion) {
        this.fdaConclusion = fdaConclusion == null ? null : fdaConclusion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FDA_MONITOR_RECORD.STATION_ID
     *
     * @return the value of FDA_MONITOR_RECORD.STATION_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getStationId() {
        return stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FDA_MONITOR_RECORD.STATION_ID
     *
     * @param stationId the value for FDA_MONITOR_RECORD.STATION_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setStationId(String stationId) {
        this.stationId = stationId == null ? null : stationId.trim();
    }
}