package com.rdc.kingsa.input.persistence.beans;

import java.util.Date;

public class LandClassification {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAND_CLASSIFICATION.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAND_CLASSIFICATION.PRIMARY_IDENTIFIER
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String primaryIdentifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAND_CLASSIFICATION.PRIMARY_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String primaryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAND_CLASSIFICATION.SECONDARY_IDENTIFIER
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String secondaryIdentifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAND_CLASSIFICATION.SECONDARY_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String secondaryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAND_CLASSIFICATION.SECONDARY_MEANINGS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String secondaryMeanings;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAND_CLASSIFICATION.CREATE_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAND_CLASSIFICATION.MODIFY_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAND_CLASSIFICATION.REMARKS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAND_CLASSIFICATION.ID
     *
     * @return the value of LAND_CLASSIFICATION.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAND_CLASSIFICATION.ID
     *
     * @param id the value for LAND_CLASSIFICATION.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAND_CLASSIFICATION.PRIMARY_IDENTIFIER
     *
     * @return the value of LAND_CLASSIFICATION.PRIMARY_IDENTIFIER
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getPrimaryIdentifier() {
        return primaryIdentifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAND_CLASSIFICATION.PRIMARY_IDENTIFIER
     *
     * @param primaryIdentifier the value for LAND_CLASSIFICATION.PRIMARY_IDENTIFIER
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setPrimaryIdentifier(String primaryIdentifier) {
        this.primaryIdentifier = primaryIdentifier == null ? null : primaryIdentifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAND_CLASSIFICATION.PRIMARY_NAME
     *
     * @return the value of LAND_CLASSIFICATION.PRIMARY_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getPrimaryName() {
        return primaryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAND_CLASSIFICATION.PRIMARY_NAME
     *
     * @param primaryName the value for LAND_CLASSIFICATION.PRIMARY_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setPrimaryName(String primaryName) {
        this.primaryName = primaryName == null ? null : primaryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAND_CLASSIFICATION.SECONDARY_IDENTIFIER
     *
     * @return the value of LAND_CLASSIFICATION.SECONDARY_IDENTIFIER
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getSecondaryIdentifier() {
        return secondaryIdentifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAND_CLASSIFICATION.SECONDARY_IDENTIFIER
     *
     * @param secondaryIdentifier the value for LAND_CLASSIFICATION.SECONDARY_IDENTIFIER
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setSecondaryIdentifier(String secondaryIdentifier) {
        this.secondaryIdentifier = secondaryIdentifier == null ? null : secondaryIdentifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAND_CLASSIFICATION.SECONDARY_NAME
     *
     * @return the value of LAND_CLASSIFICATION.SECONDARY_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getSecondaryName() {
        return secondaryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAND_CLASSIFICATION.SECONDARY_NAME
     *
     * @param secondaryName the value for LAND_CLASSIFICATION.SECONDARY_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setSecondaryName(String secondaryName) {
        this.secondaryName = secondaryName == null ? null : secondaryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAND_CLASSIFICATION.SECONDARY_MEANINGS
     *
     * @return the value of LAND_CLASSIFICATION.SECONDARY_MEANINGS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getSecondaryMeanings() {
        return secondaryMeanings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAND_CLASSIFICATION.SECONDARY_MEANINGS
     *
     * @param secondaryMeanings the value for LAND_CLASSIFICATION.SECONDARY_MEANINGS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setSecondaryMeanings(String secondaryMeanings) {
        this.secondaryMeanings = secondaryMeanings == null ? null : secondaryMeanings.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAND_CLASSIFICATION.CREATE_TIME
     *
     * @return the value of LAND_CLASSIFICATION.CREATE_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAND_CLASSIFICATION.CREATE_TIME
     *
     * @param createTime the value for LAND_CLASSIFICATION.CREATE_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAND_CLASSIFICATION.MODIFY_TIME
     *
     * @return the value of LAND_CLASSIFICATION.MODIFY_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAND_CLASSIFICATION.MODIFY_TIME
     *
     * @param modifyTime the value for LAND_CLASSIFICATION.MODIFY_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAND_CLASSIFICATION.REMARKS
     *
     * @return the value of LAND_CLASSIFICATION.REMARKS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAND_CLASSIFICATION.REMARKS
     *
     * @param remarks the value for LAND_CLASSIFICATION.REMARKS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}