package com.rdc.kingsa.input.persistence.beans;

import java.util.Date;

import com.base.dal.object.AbstractDO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel("浮游植物监测")
public class PhytoplanktonMi extends AbstractDO{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHYTOPLANKTON_MI.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    @ApiModelProperty("主键ID")
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHYTOPLANKTON_MI.SERIAL_NUMBER
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    @ApiModelProperty("序号")
    private Integer serialNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHYTOPLANKTON_MI.RIVER
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    @ApiModelProperty("河流")
    private String river;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHYTOPLANKTON_MI.SECTION_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    @ApiModelProperty("断面ID")
    private String sectionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHYTOPLANKTON_MI.SAMPLING_POINT
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    @ApiModelProperty("取样点")
    private String samplingPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHYTOPLANKTON_MI.LONGITUDE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    @ApiModelProperty("经度")
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHYTOPLANKTON_MI.LATITUDE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    @ApiModelProperty("纬度")
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHYTOPLANKTON_MI.MONITOR_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    @ApiModelProperty("监测时间")
    private Date monitorTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHYTOPLANKTON_MI.MEASURE_LINE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    @ApiModelProperty("测线")
    private String measureLine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHYTOPLANKTON_MI.WATER_DEPTH
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    @ApiModelProperty("水深")
    private Double waterDepth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHYTOPLANKTON_MI.PHYLUM
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    @ApiModelProperty("门")
    private String phylum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHYTOPLANKTON_MI.GENUS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    @ApiModelProperty("属")
    private String genus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHYTOPLANKTON_MI.SPECIES_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    @ApiModelProperty("种")
    private String speciesName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHYTOPLANKTON_MI.DENSITY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    @ApiModelProperty("密度")
    private Double density;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHYTOPLANKTON_MI.BIOMASS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    @ApiModelProperty("生物量")
    private Double biomass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHYTOPLANKTON_MI.CREATE_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    @ApiModelProperty("记录创建时间")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHYTOPLANKTON_MI.MODIFY_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    @ApiModelProperty("修改时间")
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHYTOPLANKTON_MI.REMARKS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    @ApiModelProperty("备注信息")
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHYTOPLANKTON_MI.ID
     *
     * @return the value of PHYTOPLANKTON_MI.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHYTOPLANKTON_MI.ID
     *
     * @param id the value for PHYTOPLANKTON_MI.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHYTOPLANKTON_MI.SERIAL_NUMBER
     *
     * @return the value of PHYTOPLANKTON_MI.SERIAL_NUMBER
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Integer getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHYTOPLANKTON_MI.SERIAL_NUMBER
     *
     * @param serialNumber the value for PHYTOPLANKTON_MI.SERIAL_NUMBER
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setSerialNumber(Integer serialNumber) {
        this.serialNumber = serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHYTOPLANKTON_MI.RIVER
     *
     * @return the value of PHYTOPLANKTON_MI.RIVER
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getRiver() {
        return river;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHYTOPLANKTON_MI.RIVER
     *
     * @param river the value for PHYTOPLANKTON_MI.RIVER
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setRiver(String river) {
        this.river = river == null ? null : river.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHYTOPLANKTON_MI.SECTION_ID
     *
     * @return the value of PHYTOPLANKTON_MI.SECTION_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getSectionId() {
        return sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHYTOPLANKTON_MI.SECTION_ID
     *
     * @param sectionId the value for PHYTOPLANKTON_MI.SECTION_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setSectionId(String sectionId) {
        this.sectionId = sectionId == null ? null : sectionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHYTOPLANKTON_MI.SAMPLING_POINT
     *
     * @return the value of PHYTOPLANKTON_MI.SAMPLING_POINT
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getSamplingPoint() {
        return samplingPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHYTOPLANKTON_MI.SAMPLING_POINT
     *
     * @param samplingPoint the value for PHYTOPLANKTON_MI.SAMPLING_POINT
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setSamplingPoint(String samplingPoint) {
        this.samplingPoint = samplingPoint == null ? null : samplingPoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHYTOPLANKTON_MI.LONGITUDE
     *
     * @return the value of PHYTOPLANKTON_MI.LONGITUDE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHYTOPLANKTON_MI.LONGITUDE
     *
     * @param longitude the value for PHYTOPLANKTON_MI.LONGITUDE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHYTOPLANKTON_MI.LATITUDE
     *
     * @return the value of PHYTOPLANKTON_MI.LATITUDE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHYTOPLANKTON_MI.LATITUDE
     *
     * @param latitude the value for PHYTOPLANKTON_MI.LATITUDE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHYTOPLANKTON_MI.MONITOR_TIME
     *
     * @return the value of PHYTOPLANKTON_MI.MONITOR_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Date getMonitorTime() {
        return monitorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHYTOPLANKTON_MI.MONITOR_TIME
     *
     * @param monitorTime the value for PHYTOPLANKTON_MI.MONITOR_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setMonitorTime(Date monitorTime) {
        this.monitorTime = monitorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHYTOPLANKTON_MI.MEASURE_LINE
     *
     * @return the value of PHYTOPLANKTON_MI.MEASURE_LINE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getMeasureLine() {
        return measureLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHYTOPLANKTON_MI.MEASURE_LINE
     *
     * @param measureLine the value for PHYTOPLANKTON_MI.MEASURE_LINE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setMeasureLine(String measureLine) {
        this.measureLine = measureLine == null ? null : measureLine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHYTOPLANKTON_MI.WATER_DEPTH
     *
     * @return the value of PHYTOPLANKTON_MI.WATER_DEPTH
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getWaterDepth() {
        return waterDepth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHYTOPLANKTON_MI.WATER_DEPTH
     *
     * @param waterDepth the value for PHYTOPLANKTON_MI.WATER_DEPTH
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setWaterDepth(Double waterDepth) {
        this.waterDepth = waterDepth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHYTOPLANKTON_MI.PHYLUM
     *
     * @return the value of PHYTOPLANKTON_MI.PHYLUM
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getPhylum() {
        return phylum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHYTOPLANKTON_MI.PHYLUM
     *
     * @param phylum the value for PHYTOPLANKTON_MI.PHYLUM
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setPhylum(String phylum) {
        this.phylum = phylum == null ? null : phylum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHYTOPLANKTON_MI.GENUS
     *
     * @return the value of PHYTOPLANKTON_MI.GENUS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getGenus() {
        return genus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHYTOPLANKTON_MI.GENUS
     *
     * @param genus the value for PHYTOPLANKTON_MI.GENUS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setGenus(String genus) {
        this.genus = genus == null ? null : genus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHYTOPLANKTON_MI.SPECIES_NAME
     *
     * @return the value of PHYTOPLANKTON_MI.SPECIES_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getSpeciesName() {
        return speciesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHYTOPLANKTON_MI.SPECIES_NAME
     *
     * @param speciesName the value for PHYTOPLANKTON_MI.SPECIES_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setSpeciesName(String speciesName) {
        this.speciesName = speciesName == null ? null : speciesName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHYTOPLANKTON_MI.DENSITY
     *
     * @return the value of PHYTOPLANKTON_MI.DENSITY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getDensity() {
        return density;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHYTOPLANKTON_MI.DENSITY
     *
     * @param density the value for PHYTOPLANKTON_MI.DENSITY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setDensity(Double density) {
        this.density = density;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHYTOPLANKTON_MI.BIOMASS
     *
     * @return the value of PHYTOPLANKTON_MI.BIOMASS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getBiomass() {
        return biomass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHYTOPLANKTON_MI.BIOMASS
     *
     * @param biomass the value for PHYTOPLANKTON_MI.BIOMASS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setBiomass(Double biomass) {
        this.biomass = biomass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHYTOPLANKTON_MI.CREATE_TIME
     *
     * @return the value of PHYTOPLANKTON_MI.CREATE_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHYTOPLANKTON_MI.CREATE_TIME
     *
     * @param createTime the value for PHYTOPLANKTON_MI.CREATE_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHYTOPLANKTON_MI.MODIFY_TIME
     *
     * @return the value of PHYTOPLANKTON_MI.MODIFY_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHYTOPLANKTON_MI.MODIFY_TIME
     *
     * @param modifyTime the value for PHYTOPLANKTON_MI.MODIFY_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHYTOPLANKTON_MI.REMARKS
     *
     * @return the value of PHYTOPLANKTON_MI.REMARKS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHYTOPLANKTON_MI.REMARKS
     *
     * @param remarks the value for PHYTOPLANKTON_MI.REMARKS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}