package com.rdc.kingsa.input.persistence.beans;

import java.util.Date;

public class PsFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_FILE.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_FILE.FILE_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_FILE.DESCREPTION
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String descreption;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_FILE.URL
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_FILE.TPYE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String tpye;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_FILE.UPLOADER
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String uploader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_FILE.UPLOAD_DATE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Date uploadDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_FILE.REMARKS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_FILE.STATION_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String stationId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_FILE.ID
     *
     * @return the value of PS_FILE.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_FILE.ID
     *
     * @param id the value for PS_FILE.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_FILE.FILE_NAME
     *
     * @return the value of PS_FILE.FILE_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_FILE.FILE_NAME
     *
     * @param fileName the value for PS_FILE.FILE_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_FILE.DESCREPTION
     *
     * @return the value of PS_FILE.DESCREPTION
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getDescreption() {
        return descreption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_FILE.DESCREPTION
     *
     * @param descreption the value for PS_FILE.DESCREPTION
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setDescreption(String descreption) {
        this.descreption = descreption == null ? null : descreption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_FILE.URL
     *
     * @return the value of PS_FILE.URL
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_FILE.URL
     *
     * @param url the value for PS_FILE.URL
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_FILE.TPYE
     *
     * @return the value of PS_FILE.TPYE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getTpye() {
        return tpye;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_FILE.TPYE
     *
     * @param tpye the value for PS_FILE.TPYE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setTpye(String tpye) {
        this.tpye = tpye == null ? null : tpye.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_FILE.UPLOADER
     *
     * @return the value of PS_FILE.UPLOADER
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getUploader() {
        return uploader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_FILE.UPLOADER
     *
     * @param uploader the value for PS_FILE.UPLOADER
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setUploader(String uploader) {
        this.uploader = uploader == null ? null : uploader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_FILE.UPLOAD_DATE
     *
     * @return the value of PS_FILE.UPLOAD_DATE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Date getUploadDate() {
        return uploadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_FILE.UPLOAD_DATE
     *
     * @param uploadDate the value for PS_FILE.UPLOAD_DATE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setUploadDate(Date uploadDate) {
        this.uploadDate = uploadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_FILE.REMARKS
     *
     * @return the value of PS_FILE.REMARKS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_FILE.REMARKS
     *
     * @param remarks the value for PS_FILE.REMARKS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_FILE.STATION_ID
     *
     * @return the value of PS_FILE.STATION_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getStationId() {
        return stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_FILE.STATION_ID
     *
     * @param stationId the value for PS_FILE.STATION_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setStationId(String stationId) {
        this.stationId = stationId == null ? null : stationId.trim();
    }
}