package com.rdc.kingsa.input.persistence.beans;

import java.util.Date;

public class RareEndemicFish {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RARE_ENDEMIC_FISH.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RARE_ENDEMIC_FISH.BIO_ORDER
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String bioOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RARE_ENDEMIC_FISH.FAMILY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String family;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RARE_ENDEMIC_FISH.SUB_FAMILY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String subFamily;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RARE_ENDEMIC_FISH.GENUS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String genus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RARE_ENDEMIC_FISH.SPECIES_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String speciesName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RARE_ENDEMIC_FISH.CREATE_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RARE_ENDEMIC_FISH.MODIFY_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RARE_ENDEMIC_FISH.REMARKS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RARE_ENDEMIC_FISH.ID
     *
     * @return the value of RARE_ENDEMIC_FISH.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RARE_ENDEMIC_FISH.ID
     *
     * @param id the value for RARE_ENDEMIC_FISH.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RARE_ENDEMIC_FISH.BIO_ORDER
     *
     * @return the value of RARE_ENDEMIC_FISH.BIO_ORDER
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getBioOrder() {
        return bioOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RARE_ENDEMIC_FISH.BIO_ORDER
     *
     * @param bioOrder the value for RARE_ENDEMIC_FISH.BIO_ORDER
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setBioOrder(String bioOrder) {
        this.bioOrder = bioOrder == null ? null : bioOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RARE_ENDEMIC_FISH.FAMILY
     *
     * @return the value of RARE_ENDEMIC_FISH.FAMILY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getFamily() {
        return family;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RARE_ENDEMIC_FISH.FAMILY
     *
     * @param family the value for RARE_ENDEMIC_FISH.FAMILY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setFamily(String family) {
        this.family = family == null ? null : family.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RARE_ENDEMIC_FISH.SUB_FAMILY
     *
     * @return the value of RARE_ENDEMIC_FISH.SUB_FAMILY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getSubFamily() {
        return subFamily;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RARE_ENDEMIC_FISH.SUB_FAMILY
     *
     * @param subFamily the value for RARE_ENDEMIC_FISH.SUB_FAMILY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setSubFamily(String subFamily) {
        this.subFamily = subFamily == null ? null : subFamily.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RARE_ENDEMIC_FISH.GENUS
     *
     * @return the value of RARE_ENDEMIC_FISH.GENUS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getGenus() {
        return genus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RARE_ENDEMIC_FISH.GENUS
     *
     * @param genus the value for RARE_ENDEMIC_FISH.GENUS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setGenus(String genus) {
        this.genus = genus == null ? null : genus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RARE_ENDEMIC_FISH.SPECIES_NAME
     *
     * @return the value of RARE_ENDEMIC_FISH.SPECIES_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getSpeciesName() {
        return speciesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RARE_ENDEMIC_FISH.SPECIES_NAME
     *
     * @param speciesName the value for RARE_ENDEMIC_FISH.SPECIES_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setSpeciesName(String speciesName) {
        this.speciesName = speciesName == null ? null : speciesName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RARE_ENDEMIC_FISH.CREATE_TIME
     *
     * @return the value of RARE_ENDEMIC_FISH.CREATE_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RARE_ENDEMIC_FISH.CREATE_TIME
     *
     * @param createTime the value for RARE_ENDEMIC_FISH.CREATE_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RARE_ENDEMIC_FISH.MODIFY_TIME
     *
     * @return the value of RARE_ENDEMIC_FISH.MODIFY_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RARE_ENDEMIC_FISH.MODIFY_TIME
     *
     * @param modifyTime the value for RARE_ENDEMIC_FISH.MODIFY_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RARE_ENDEMIC_FISH.REMARKS
     *
     * @return the value of RARE_ENDEMIC_FISH.REMARKS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RARE_ENDEMIC_FISH.REMARKS
     *
     * @param remarks the value for RARE_ENDEMIC_FISH.REMARKS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}