package com.rdc.kingsa.input.persistence.beans;

import java.util.Date;

import com.base.dal.object.AbstractDO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel("鱼类产卵场和繁殖生态")
public class ReproductionEcology extends AbstractDO{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPRODUCTION_ECOLOGY.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    @ApiModelProperty("主键ID")
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPRODUCTION_ECOLOGY.SECTION_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    @ApiModelProperty("断面ID")
    private String sectionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPRODUCTION_ECOLOGY.SECTION_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    @ApiModelProperty("断面名称")
    private String sectionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPRODUCTION_ECOLOGY.MONITOR_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    @ApiModelProperty("监测时间")
    private Date monitorTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPRODUCTION_ECOLOGY.FRY_NUMBER
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    @ApiModelProperty("卵苗数")
    private Integer fryNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPRODUCTION_ECOLOGY.FRY_RUNOFF
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    @ApiModelProperty("卵径流量")
    private Double fryRunoff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPRODUCTION_ECOLOGY.WATER_TEMP
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    @ApiModelProperty("水温")
    private Double waterTemp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPRODUCTION_ECOLOGY.FRY_FLOWS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    @ApiModelProperty("流量   ")
    private Long fryFlows;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPRODUCTION_ECOLOGY.TRANSPARENCY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    @ApiModelProperty("透明度")
    private Integer transparency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPRODUCTION_ECOLOGY.DISSOLVE_OXYGEN
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    @ApiModelProperty("DissolveOxygen")
    private Double dissolveOxygen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPRODUCTION_ECOLOGY.CREATE_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    @ApiModelProperty("创建时间")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPRODUCTION_ECOLOGY.MODIFY_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    @ApiModelProperty("修改时间")
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPRODUCTION_ECOLOGY.REMARKS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    @ApiModelProperty("备注信息")
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPRODUCTION_ECOLOGY.ID
     *
     * @return the value of REPRODUCTION_ECOLOGY.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPRODUCTION_ECOLOGY.ID
     *
     * @param id the value for REPRODUCTION_ECOLOGY.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPRODUCTION_ECOLOGY.SECTION_ID
     *
     * @return the value of REPRODUCTION_ECOLOGY.SECTION_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getSectionId() {
        return sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPRODUCTION_ECOLOGY.SECTION_ID
     *
     * @param sectionId the value for REPRODUCTION_ECOLOGY.SECTION_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setSectionId(String sectionId) {
        this.sectionId = sectionId == null ? null : sectionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPRODUCTION_ECOLOGY.SECTION_NAME
     *
     * @return the value of REPRODUCTION_ECOLOGY.SECTION_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getSectionName() {
        return sectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPRODUCTION_ECOLOGY.SECTION_NAME
     *
     * @param sectionName the value for REPRODUCTION_ECOLOGY.SECTION_NAME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setSectionName(String sectionName) {
        this.sectionName = sectionName == null ? null : sectionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPRODUCTION_ECOLOGY.MONITOR_TIME
     *
     * @return the value of REPRODUCTION_ECOLOGY.MONITOR_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Date getMonitorTime() {
        return monitorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPRODUCTION_ECOLOGY.MONITOR_TIME
     *
     * @param monitorTime the value for REPRODUCTION_ECOLOGY.MONITOR_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setMonitorTime(Date monitorTime) {
        this.monitorTime = monitorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPRODUCTION_ECOLOGY.FRY_NUMBER
     *
     * @return the value of REPRODUCTION_ECOLOGY.FRY_NUMBER
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Integer getFryNumber() {
        return fryNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPRODUCTION_ECOLOGY.FRY_NUMBER
     *
     * @param fryNumber the value for REPRODUCTION_ECOLOGY.FRY_NUMBER
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setFryNumber(Integer fryNumber) {
        this.fryNumber = fryNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPRODUCTION_ECOLOGY.FRY_RUNOFF
     *
     * @return the value of REPRODUCTION_ECOLOGY.FRY_RUNOFF
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getFryRunoff() {
        return fryRunoff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPRODUCTION_ECOLOGY.FRY_RUNOFF
     *
     * @param fryRunoff the value for REPRODUCTION_ECOLOGY.FRY_RUNOFF
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setFryRunoff(Double fryRunoff) {
        this.fryRunoff = fryRunoff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPRODUCTION_ECOLOGY.WATER_TEMP
     *
     * @return the value of REPRODUCTION_ECOLOGY.WATER_TEMP
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getWaterTemp() {
        return waterTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPRODUCTION_ECOLOGY.WATER_TEMP
     *
     * @param waterTemp the value for REPRODUCTION_ECOLOGY.WATER_TEMP
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setWaterTemp(Double waterTemp) {
        this.waterTemp = waterTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPRODUCTION_ECOLOGY.FRY_FLOWS
     *
     * @return the value of REPRODUCTION_ECOLOGY.FRY_FLOWS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Long getFryFlows() {
        return fryFlows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPRODUCTION_ECOLOGY.FRY_FLOWS
     *
     * @param fryFlows the value for REPRODUCTION_ECOLOGY.FRY_FLOWS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setFryFlows(Long fryFlows) {
        this.fryFlows = fryFlows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPRODUCTION_ECOLOGY.TRANSPARENCY
     *
     * @return the value of REPRODUCTION_ECOLOGY.TRANSPARENCY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Integer getTransparency() {
        return transparency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPRODUCTION_ECOLOGY.TRANSPARENCY
     *
     * @param transparency the value for REPRODUCTION_ECOLOGY.TRANSPARENCY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setTransparency(Integer transparency) {
        this.transparency = transparency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPRODUCTION_ECOLOGY.DISSOLVE_OXYGEN
     *
     * @return the value of REPRODUCTION_ECOLOGY.DISSOLVE_OXYGEN
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getDissolveOxygen() {
        return dissolveOxygen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPRODUCTION_ECOLOGY.DISSOLVE_OXYGEN
     *
     * @param dissolveOxygen the value for REPRODUCTION_ECOLOGY.DISSOLVE_OXYGEN
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setDissolveOxygen(Double dissolveOxygen) {
        this.dissolveOxygen = dissolveOxygen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPRODUCTION_ECOLOGY.CREATE_TIME
     *
     * @return the value of REPRODUCTION_ECOLOGY.CREATE_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPRODUCTION_ECOLOGY.CREATE_TIME
     *
     * @param createTime the value for REPRODUCTION_ECOLOGY.CREATE_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPRODUCTION_ECOLOGY.MODIFY_TIME
     *
     * @return the value of REPRODUCTION_ECOLOGY.MODIFY_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPRODUCTION_ECOLOGY.MODIFY_TIME
     *
     * @param modifyTime the value for REPRODUCTION_ECOLOGY.MODIFY_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPRODUCTION_ECOLOGY.REMARKS
     *
     * @return the value of REPRODUCTION_ECOLOGY.REMARKS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPRODUCTION_ECOLOGY.REMARKS
     *
     * @param remarks the value for REPRODUCTION_ECOLOGY.REMARKS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}