package com.rdc.kingsa.input.persistence.beans;

import java.util.Date;

public class SwtMi {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWT_MI.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWT_MI.SECTION_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String sectionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWT_MI.MONITOR_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Date monitorTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWT_MI.WATER_TEMPER
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double waterTemper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWT_MI.CREATE_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWT_MI.MODIFY_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWT_MI.REMARKS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWT_MI.ID
     *
     * @return the value of SWT_MI.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWT_MI.ID
     *
     * @param id the value for SWT_MI.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWT_MI.SECTION_ID
     *
     * @return the value of SWT_MI.SECTION_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getSectionId() {
        return sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWT_MI.SECTION_ID
     *
     * @param sectionId the value for SWT_MI.SECTION_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setSectionId(String sectionId) {
        this.sectionId = sectionId == null ? null : sectionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWT_MI.MONITOR_TIME
     *
     * @return the value of SWT_MI.MONITOR_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Date getMonitorTime() {
        return monitorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWT_MI.MONITOR_TIME
     *
     * @param monitorTime the value for SWT_MI.MONITOR_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setMonitorTime(Date monitorTime) {
        this.monitorTime = monitorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWT_MI.WATER_TEMPER
     *
     * @return the value of SWT_MI.WATER_TEMPER
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getWaterTemper() {
        return waterTemper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWT_MI.WATER_TEMPER
     *
     * @param waterTemper the value for SWT_MI.WATER_TEMPER
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setWaterTemper(Double waterTemper) {
        this.waterTemper = waterTemper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWT_MI.CREATE_TIME
     *
     * @return the value of SWT_MI.CREATE_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWT_MI.CREATE_TIME
     *
     * @param createTime the value for SWT_MI.CREATE_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWT_MI.MODIFY_TIME
     *
     * @return the value of SWT_MI.MODIFY_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWT_MI.MODIFY_TIME
     *
     * @param modifyTime the value for SWT_MI.MODIFY_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWT_MI.REMARKS
     *
     * @return the value of SWT_MI.REMARKS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWT_MI.REMARKS
     *
     * @param remarks the value for SWT_MI.REMARKS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}