package com.rdc.kingsa.input.persistence.beans;

import java.util.Date;

public class WaterQualityEstimateCpoi {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_ESTIMATE_CPOI.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_ESTIMATE_CPOI.SEC_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String secId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_ESTIMATE_CPOI.QA_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String qaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_ESTIMATE_CPOI.MONITOR_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Date monitorTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_ESTIMATE_CPOI.EVALUATION_METHOD
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String evaluationMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_ESTIMATE_CPOI.PH_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Float phT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_ESTIMATE_CPOI.DIS_OXYGEN_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Float disOxygenT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_ESTIMATE_CPOI.PERMANGANATE_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Float permanganateT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_ESTIMATE_CPOI.OX_DEMAND_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Float oxDemandT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_ESTIMATE_CPOI.BO_DEMAND_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Float boDemandT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_ESTIMATE_CPOI.AMMONIA_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Float ammoniaT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_ESTIMATE_CPOI.PHOSPHORUS_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Float phosphorusT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_ESTIMATE_CPOI.COPPER_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Float copperT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_ESTIMATE_CPOI.ZINC_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Float zincT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_ESTIMATE_CPOI.FLUORIDE_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Float fluorideT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_ESTIMATE_CPOI.SELENIUM_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Float seleniumT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_ESTIMATE_CPOI.ARSENIC_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Float arsenicT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_ESTIMATE_CPOI.MERCURY_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Float mercuryT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_ESTIMATE_CPOI.CADMIUM_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Float cadmiumT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_ESTIMATE_CPOI.CHROMIUM_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Float chromiumT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_ESTIMATE_CPOI.LEAD_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Float leadT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_ESTIMATE_CPOI.CYANIDE_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Float cyanideT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_ESTIMATE_CPOI.PHENOL_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Float phenolT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_ESTIMATE_CPOI.PETROLEUM_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Float petroleumT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_ESTIMATE_CPOI.SURFACTANT_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Float surfactantT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_ESTIMATE_CPOI.SULFIDE_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Float sulfideT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_ESTIMATE_CPOI.QA_TYPE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Float qaType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_ESTIMATE_CPOI.QA_STATUS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String qaStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_ESTIMATE_CPOI.CREATE_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_ESTIMATE_CPOI.MODIFY_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_ESTIMATE_CPOI.REMARKS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_ESTIMATE_CPOI.ID
     *
     * @return the value of WATER_QUALITY_ESTIMATE_CPOI.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_ESTIMATE_CPOI.ID
     *
     * @param id the value for WATER_QUALITY_ESTIMATE_CPOI.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_ESTIMATE_CPOI.SEC_ID
     *
     * @return the value of WATER_QUALITY_ESTIMATE_CPOI.SEC_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getSecId() {
        return secId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_ESTIMATE_CPOI.SEC_ID
     *
     * @param secId the value for WATER_QUALITY_ESTIMATE_CPOI.SEC_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setSecId(String secId) {
        this.secId = secId == null ? null : secId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_ESTIMATE_CPOI.QA_ID
     *
     * @return the value of WATER_QUALITY_ESTIMATE_CPOI.QA_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getQaId() {
        return qaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_ESTIMATE_CPOI.QA_ID
     *
     * @param qaId the value for WATER_QUALITY_ESTIMATE_CPOI.QA_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setQaId(String qaId) {
        this.qaId = qaId == null ? null : qaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_ESTIMATE_CPOI.MONITOR_TIME
     *
     * @return the value of WATER_QUALITY_ESTIMATE_CPOI.MONITOR_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Date getMonitorTime() {
        return monitorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_ESTIMATE_CPOI.MONITOR_TIME
     *
     * @param monitorTime the value for WATER_QUALITY_ESTIMATE_CPOI.MONITOR_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setMonitorTime(Date monitorTime) {
        this.monitorTime = monitorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_ESTIMATE_CPOI.EVALUATION_METHOD
     *
     * @return the value of WATER_QUALITY_ESTIMATE_CPOI.EVALUATION_METHOD
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getEvaluationMethod() {
        return evaluationMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_ESTIMATE_CPOI.EVALUATION_METHOD
     *
     * @param evaluationMethod the value for WATER_QUALITY_ESTIMATE_CPOI.EVALUATION_METHOD
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setEvaluationMethod(String evaluationMethod) {
        this.evaluationMethod = evaluationMethod == null ? null : evaluationMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_ESTIMATE_CPOI.PH_T
     *
     * @return the value of WATER_QUALITY_ESTIMATE_CPOI.PH_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Float getPhT() {
        return phT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_ESTIMATE_CPOI.PH_T
     *
     * @param phT the value for WATER_QUALITY_ESTIMATE_CPOI.PH_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setPhT(Float phT) {
        this.phT = phT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_ESTIMATE_CPOI.DIS_OXYGEN_T
     *
     * @return the value of WATER_QUALITY_ESTIMATE_CPOI.DIS_OXYGEN_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Float getDisOxygenT() {
        return disOxygenT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_ESTIMATE_CPOI.DIS_OXYGEN_T
     *
     * @param disOxygenT the value for WATER_QUALITY_ESTIMATE_CPOI.DIS_OXYGEN_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setDisOxygenT(Float disOxygenT) {
        this.disOxygenT = disOxygenT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_ESTIMATE_CPOI.PERMANGANATE_T
     *
     * @return the value of WATER_QUALITY_ESTIMATE_CPOI.PERMANGANATE_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Float getPermanganateT() {
        return permanganateT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_ESTIMATE_CPOI.PERMANGANATE_T
     *
     * @param permanganateT the value for WATER_QUALITY_ESTIMATE_CPOI.PERMANGANATE_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setPermanganateT(Float permanganateT) {
        this.permanganateT = permanganateT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_ESTIMATE_CPOI.OX_DEMAND_T
     *
     * @return the value of WATER_QUALITY_ESTIMATE_CPOI.OX_DEMAND_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Float getOxDemandT() {
        return oxDemandT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_ESTIMATE_CPOI.OX_DEMAND_T
     *
     * @param oxDemandT the value for WATER_QUALITY_ESTIMATE_CPOI.OX_DEMAND_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setOxDemandT(Float oxDemandT) {
        this.oxDemandT = oxDemandT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_ESTIMATE_CPOI.BO_DEMAND_T
     *
     * @return the value of WATER_QUALITY_ESTIMATE_CPOI.BO_DEMAND_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Float getBoDemandT() {
        return boDemandT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_ESTIMATE_CPOI.BO_DEMAND_T
     *
     * @param boDemandT the value for WATER_QUALITY_ESTIMATE_CPOI.BO_DEMAND_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setBoDemandT(Float boDemandT) {
        this.boDemandT = boDemandT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_ESTIMATE_CPOI.AMMONIA_T
     *
     * @return the value of WATER_QUALITY_ESTIMATE_CPOI.AMMONIA_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Float getAmmoniaT() {
        return ammoniaT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_ESTIMATE_CPOI.AMMONIA_T
     *
     * @param ammoniaT the value for WATER_QUALITY_ESTIMATE_CPOI.AMMONIA_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setAmmoniaT(Float ammoniaT) {
        this.ammoniaT = ammoniaT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_ESTIMATE_CPOI.PHOSPHORUS_T
     *
     * @return the value of WATER_QUALITY_ESTIMATE_CPOI.PHOSPHORUS_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Float getPhosphorusT() {
        return phosphorusT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_ESTIMATE_CPOI.PHOSPHORUS_T
     *
     * @param phosphorusT the value for WATER_QUALITY_ESTIMATE_CPOI.PHOSPHORUS_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setPhosphorusT(Float phosphorusT) {
        this.phosphorusT = phosphorusT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_ESTIMATE_CPOI.COPPER_T
     *
     * @return the value of WATER_QUALITY_ESTIMATE_CPOI.COPPER_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Float getCopperT() {
        return copperT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_ESTIMATE_CPOI.COPPER_T
     *
     * @param copperT the value for WATER_QUALITY_ESTIMATE_CPOI.COPPER_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setCopperT(Float copperT) {
        this.copperT = copperT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_ESTIMATE_CPOI.ZINC_T
     *
     * @return the value of WATER_QUALITY_ESTIMATE_CPOI.ZINC_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Float getZincT() {
        return zincT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_ESTIMATE_CPOI.ZINC_T
     *
     * @param zincT the value for WATER_QUALITY_ESTIMATE_CPOI.ZINC_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setZincT(Float zincT) {
        this.zincT = zincT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_ESTIMATE_CPOI.FLUORIDE_T
     *
     * @return the value of WATER_QUALITY_ESTIMATE_CPOI.FLUORIDE_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Float getFluorideT() {
        return fluorideT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_ESTIMATE_CPOI.FLUORIDE_T
     *
     * @param fluorideT the value for WATER_QUALITY_ESTIMATE_CPOI.FLUORIDE_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setFluorideT(Float fluorideT) {
        this.fluorideT = fluorideT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_ESTIMATE_CPOI.SELENIUM_T
     *
     * @return the value of WATER_QUALITY_ESTIMATE_CPOI.SELENIUM_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Float getSeleniumT() {
        return seleniumT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_ESTIMATE_CPOI.SELENIUM_T
     *
     * @param seleniumT the value for WATER_QUALITY_ESTIMATE_CPOI.SELENIUM_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setSeleniumT(Float seleniumT) {
        this.seleniumT = seleniumT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_ESTIMATE_CPOI.ARSENIC_T
     *
     * @return the value of WATER_QUALITY_ESTIMATE_CPOI.ARSENIC_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Float getArsenicT() {
        return arsenicT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_ESTIMATE_CPOI.ARSENIC_T
     *
     * @param arsenicT the value for WATER_QUALITY_ESTIMATE_CPOI.ARSENIC_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setArsenicT(Float arsenicT) {
        this.arsenicT = arsenicT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_ESTIMATE_CPOI.MERCURY_T
     *
     * @return the value of WATER_QUALITY_ESTIMATE_CPOI.MERCURY_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Float getMercuryT() {
        return mercuryT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_ESTIMATE_CPOI.MERCURY_T
     *
     * @param mercuryT the value for WATER_QUALITY_ESTIMATE_CPOI.MERCURY_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setMercuryT(Float mercuryT) {
        this.mercuryT = mercuryT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_ESTIMATE_CPOI.CADMIUM_T
     *
     * @return the value of WATER_QUALITY_ESTIMATE_CPOI.CADMIUM_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Float getCadmiumT() {
        return cadmiumT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_ESTIMATE_CPOI.CADMIUM_T
     *
     * @param cadmiumT the value for WATER_QUALITY_ESTIMATE_CPOI.CADMIUM_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setCadmiumT(Float cadmiumT) {
        this.cadmiumT = cadmiumT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_ESTIMATE_CPOI.CHROMIUM_T
     *
     * @return the value of WATER_QUALITY_ESTIMATE_CPOI.CHROMIUM_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Float getChromiumT() {
        return chromiumT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_ESTIMATE_CPOI.CHROMIUM_T
     *
     * @param chromiumT the value for WATER_QUALITY_ESTIMATE_CPOI.CHROMIUM_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setChromiumT(Float chromiumT) {
        this.chromiumT = chromiumT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_ESTIMATE_CPOI.LEAD_T
     *
     * @return the value of WATER_QUALITY_ESTIMATE_CPOI.LEAD_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Float getLeadT() {
        return leadT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_ESTIMATE_CPOI.LEAD_T
     *
     * @param leadT the value for WATER_QUALITY_ESTIMATE_CPOI.LEAD_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setLeadT(Float leadT) {
        this.leadT = leadT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_ESTIMATE_CPOI.CYANIDE_T
     *
     * @return the value of WATER_QUALITY_ESTIMATE_CPOI.CYANIDE_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Float getCyanideT() {
        return cyanideT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_ESTIMATE_CPOI.CYANIDE_T
     *
     * @param cyanideT the value for WATER_QUALITY_ESTIMATE_CPOI.CYANIDE_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setCyanideT(Float cyanideT) {
        this.cyanideT = cyanideT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_ESTIMATE_CPOI.PHENOL_T
     *
     * @return the value of WATER_QUALITY_ESTIMATE_CPOI.PHENOL_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Float getPhenolT() {
        return phenolT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_ESTIMATE_CPOI.PHENOL_T
     *
     * @param phenolT the value for WATER_QUALITY_ESTIMATE_CPOI.PHENOL_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setPhenolT(Float phenolT) {
        this.phenolT = phenolT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_ESTIMATE_CPOI.PETROLEUM_T
     *
     * @return the value of WATER_QUALITY_ESTIMATE_CPOI.PETROLEUM_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Float getPetroleumT() {
        return petroleumT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_ESTIMATE_CPOI.PETROLEUM_T
     *
     * @param petroleumT the value for WATER_QUALITY_ESTIMATE_CPOI.PETROLEUM_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setPetroleumT(Float petroleumT) {
        this.petroleumT = petroleumT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_ESTIMATE_CPOI.SURFACTANT_T
     *
     * @return the value of WATER_QUALITY_ESTIMATE_CPOI.SURFACTANT_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Float getSurfactantT() {
        return surfactantT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_ESTIMATE_CPOI.SURFACTANT_T
     *
     * @param surfactantT the value for WATER_QUALITY_ESTIMATE_CPOI.SURFACTANT_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setSurfactantT(Float surfactantT) {
        this.surfactantT = surfactantT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_ESTIMATE_CPOI.SULFIDE_T
     *
     * @return the value of WATER_QUALITY_ESTIMATE_CPOI.SULFIDE_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Float getSulfideT() {
        return sulfideT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_ESTIMATE_CPOI.SULFIDE_T
     *
     * @param sulfideT the value for WATER_QUALITY_ESTIMATE_CPOI.SULFIDE_T
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setSulfideT(Float sulfideT) {
        this.sulfideT = sulfideT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_ESTIMATE_CPOI.QA_TYPE
     *
     * @return the value of WATER_QUALITY_ESTIMATE_CPOI.QA_TYPE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Float getQaType() {
        return qaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_ESTIMATE_CPOI.QA_TYPE
     *
     * @param qaType the value for WATER_QUALITY_ESTIMATE_CPOI.QA_TYPE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setQaType(Float qaType) {
        this.qaType = qaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_ESTIMATE_CPOI.QA_STATUS
     *
     * @return the value of WATER_QUALITY_ESTIMATE_CPOI.QA_STATUS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getQaStatus() {
        return qaStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_ESTIMATE_CPOI.QA_STATUS
     *
     * @param qaStatus the value for WATER_QUALITY_ESTIMATE_CPOI.QA_STATUS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setQaStatus(String qaStatus) {
        this.qaStatus = qaStatus == null ? null : qaStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_ESTIMATE_CPOI.CREATE_TIME
     *
     * @return the value of WATER_QUALITY_ESTIMATE_CPOI.CREATE_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_ESTIMATE_CPOI.CREATE_TIME
     *
     * @param createTime the value for WATER_QUALITY_ESTIMATE_CPOI.CREATE_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_ESTIMATE_CPOI.MODIFY_TIME
     *
     * @return the value of WATER_QUALITY_ESTIMATE_CPOI.MODIFY_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_ESTIMATE_CPOI.MODIFY_TIME
     *
     * @param modifyTime the value for WATER_QUALITY_ESTIMATE_CPOI.MODIFY_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_ESTIMATE_CPOI.REMARKS
     *
     * @return the value of WATER_QUALITY_ESTIMATE_CPOI.REMARKS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_ESTIMATE_CPOI.REMARKS
     *
     * @param remarks the value for WATER_QUALITY_ESTIMATE_CPOI.REMARKS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}