package com.rdc.kingsa.input.persistence.beans;

import java.util.Date;

public class WaterQualityFc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.PROCESS_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String processId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.SEC_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String secId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.MONITOR_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Date monitorTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.WATER_TEMP
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double waterTemp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.WATER_TEMP_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String waterTempSy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.WATER_TEMP_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String waterTempTy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.PH_VALUE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double phValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.PH_VALUE_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String phValueSy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.PH_VALUE_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String phValueTy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.DIS_OXYGEN
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double disOxygen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.DIS_OXYGEN_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String disOxygenSy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.DIS_OXYGEN_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String disOxygenTy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.PERMANGANATE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double permanganate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.PERMANGANATE_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String permanganateSy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.PERMANGANATE_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String permanganateTy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.OX_DEMAND
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double oxDemand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.OX_DEMAND_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String oxDemandSy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.OX_DEMAND_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String oxDemandTy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.BO_DEMAND
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double boDemand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.BO_DEMAND_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String boDemandSy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.BO_DEMAND_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String boDemandTy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.AMMONIA
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double ammonia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.AMMONIA_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String ammoniaSy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.AMMONIA_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String ammoniaTy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.PHOSPHORUS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double phosphorus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.PHOSPHORUS_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String phosphorusSy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.PHOSPHORUS_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String phosphorusTy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.NITROGEN
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double nitrogen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.NITROGEN_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String nitrogenSy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.NITROGEN_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String nitrogenTy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.COPPER
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double copper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.COPPER_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String copperSy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.COPPER_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String copperTy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.ZINC
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double zinc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.ZINC_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String zincSy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.ZINC_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String zincTy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.FLUORIDE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double fluoride;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.FLUORIDE_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String fluorideSy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.FLUORIDE_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String fluorideTy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.SELENIUM
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double selenium;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.SELENIUM_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String seleniumSy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.SELENIUM_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String seleniumTy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.ARSENIC
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double arsenic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.ARSENIC_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String arsenicSy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.ARSENIC_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String arsenicTy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.MERCURY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double mercury;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.MERCURY_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String mercurySy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.MERCURY_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String mercuryTy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.CADMIUM
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double cadmium;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.CADMIUM_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String cadmiumSy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.CADMIUM_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String cadmiumTy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.CHROMIUM
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double chromium;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.CHROMIUM_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String chromiumSy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.CHROMIUM_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String chromiumTy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.LEAD
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double lead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.LEAD_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String leadSy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.LEAD_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String leadTy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.CYANIDE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double cyanide;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.CYANIDE_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String cyanideSy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.CYANIDE_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String cyanideTy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.PHENOL
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double phenol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.PHENOL_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String phenolSy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.PHENOL_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String phenolTy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.PETROLEUM
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double petroleum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.PETROLEUM_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String petroleumSy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.PETROLEUM_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String petroleumTy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.SURFACTANT
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double surfactant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.SURFACTANT_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String surfactantSy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.SURFACTANT_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String surfactantTy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.SULFIDE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double sulfide;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.SULFIDE_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String sulfideSy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.SULFIDE_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String sulfideTy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.COLIFORM
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double coliform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.COLIFORM_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String coliformSy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.COLIFORM_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String coliformTy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.CHLOR_A
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double chlorA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.CHLOR_A_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String chlorASy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.CHLOR_A_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String chlorATy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.TRANSPARENCY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double transparency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.TRANSPARENCY_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String transparencySy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.TRANSPARENCY_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String transparencyTy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.SUSPENDED
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double suspended;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.SUSPENDED_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String suspendedSy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.SUSPENDED_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String suspendedTy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.QA_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String qaTy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.MON_UNIT
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String monUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.MONITOR
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String monitor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.INPUTER
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String inputer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.AUDITOR
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String auditor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.CREATE_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.MODIFY_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.REMARKS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WATER_QUALITY_FC.REPORT_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String reportId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.ID
     *
     * @return the value of WATER_QUALITY_FC.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.ID
     *
     * @param id the value for WATER_QUALITY_FC.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.PROCESS_ID
     *
     * @return the value of WATER_QUALITY_FC.PROCESS_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getProcessId() {
        return processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.PROCESS_ID
     *
     * @param processId the value for WATER_QUALITY_FC.PROCESS_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setProcessId(String processId) {
        this.processId = processId == null ? null : processId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.SEC_ID
     *
     * @return the value of WATER_QUALITY_FC.SEC_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getSecId() {
        return secId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.SEC_ID
     *
     * @param secId the value for WATER_QUALITY_FC.SEC_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setSecId(String secId) {
        this.secId = secId == null ? null : secId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.MONITOR_TIME
     *
     * @return the value of WATER_QUALITY_FC.MONITOR_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Date getMonitorTime() {
        return monitorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.MONITOR_TIME
     *
     * @param monitorTime the value for WATER_QUALITY_FC.MONITOR_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setMonitorTime(Date monitorTime) {
        this.monitorTime = monitorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.WATER_TEMP
     *
     * @return the value of WATER_QUALITY_FC.WATER_TEMP
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getWaterTemp() {
        return waterTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.WATER_TEMP
     *
     * @param waterTemp the value for WATER_QUALITY_FC.WATER_TEMP
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setWaterTemp(Double waterTemp) {
        this.waterTemp = waterTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.WATER_TEMP_SY
     *
     * @return the value of WATER_QUALITY_FC.WATER_TEMP_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getWaterTempSy() {
        return waterTempSy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.WATER_TEMP_SY
     *
     * @param waterTempSy the value for WATER_QUALITY_FC.WATER_TEMP_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setWaterTempSy(String waterTempSy) {
        this.waterTempSy = waterTempSy == null ? null : waterTempSy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.WATER_TEMP_TY
     *
     * @return the value of WATER_QUALITY_FC.WATER_TEMP_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getWaterTempTy() {
        return waterTempTy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.WATER_TEMP_TY
     *
     * @param waterTempTy the value for WATER_QUALITY_FC.WATER_TEMP_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setWaterTempTy(String waterTempTy) {
        this.waterTempTy = waterTempTy == null ? null : waterTempTy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.PH_VALUE
     *
     * @return the value of WATER_QUALITY_FC.PH_VALUE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getPhValue() {
        return phValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.PH_VALUE
     *
     * @param phValue the value for WATER_QUALITY_FC.PH_VALUE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setPhValue(Double phValue) {
        this.phValue = phValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.PH_VALUE_SY
     *
     * @return the value of WATER_QUALITY_FC.PH_VALUE_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getPhValueSy() {
        return phValueSy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.PH_VALUE_SY
     *
     * @param phValueSy the value for WATER_QUALITY_FC.PH_VALUE_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setPhValueSy(String phValueSy) {
        this.phValueSy = phValueSy == null ? null : phValueSy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.PH_VALUE_TY
     *
     * @return the value of WATER_QUALITY_FC.PH_VALUE_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getPhValueTy() {
        return phValueTy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.PH_VALUE_TY
     *
     * @param phValueTy the value for WATER_QUALITY_FC.PH_VALUE_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setPhValueTy(String phValueTy) {
        this.phValueTy = phValueTy == null ? null : phValueTy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.DIS_OXYGEN
     *
     * @return the value of WATER_QUALITY_FC.DIS_OXYGEN
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getDisOxygen() {
        return disOxygen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.DIS_OXYGEN
     *
     * @param disOxygen the value for WATER_QUALITY_FC.DIS_OXYGEN
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setDisOxygen(Double disOxygen) {
        this.disOxygen = disOxygen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.DIS_OXYGEN_SY
     *
     * @return the value of WATER_QUALITY_FC.DIS_OXYGEN_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getDisOxygenSy() {
        return disOxygenSy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.DIS_OXYGEN_SY
     *
     * @param disOxygenSy the value for WATER_QUALITY_FC.DIS_OXYGEN_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setDisOxygenSy(String disOxygenSy) {
        this.disOxygenSy = disOxygenSy == null ? null : disOxygenSy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.DIS_OXYGEN_TY
     *
     * @return the value of WATER_QUALITY_FC.DIS_OXYGEN_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getDisOxygenTy() {
        return disOxygenTy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.DIS_OXYGEN_TY
     *
     * @param disOxygenTy the value for WATER_QUALITY_FC.DIS_OXYGEN_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setDisOxygenTy(String disOxygenTy) {
        this.disOxygenTy = disOxygenTy == null ? null : disOxygenTy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.PERMANGANATE
     *
     * @return the value of WATER_QUALITY_FC.PERMANGANATE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getPermanganate() {
        return permanganate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.PERMANGANATE
     *
     * @param permanganate the value for WATER_QUALITY_FC.PERMANGANATE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setPermanganate(Double permanganate) {
        this.permanganate = permanganate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.PERMANGANATE_SY
     *
     * @return the value of WATER_QUALITY_FC.PERMANGANATE_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getPermanganateSy() {
        return permanganateSy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.PERMANGANATE_SY
     *
     * @param permanganateSy the value for WATER_QUALITY_FC.PERMANGANATE_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setPermanganateSy(String permanganateSy) {
        this.permanganateSy = permanganateSy == null ? null : permanganateSy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.PERMANGANATE_TY
     *
     * @return the value of WATER_QUALITY_FC.PERMANGANATE_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getPermanganateTy() {
        return permanganateTy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.PERMANGANATE_TY
     *
     * @param permanganateTy the value for WATER_QUALITY_FC.PERMANGANATE_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setPermanganateTy(String permanganateTy) {
        this.permanganateTy = permanganateTy == null ? null : permanganateTy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.OX_DEMAND
     *
     * @return the value of WATER_QUALITY_FC.OX_DEMAND
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getOxDemand() {
        return oxDemand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.OX_DEMAND
     *
     * @param oxDemand the value for WATER_QUALITY_FC.OX_DEMAND
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setOxDemand(Double oxDemand) {
        this.oxDemand = oxDemand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.OX_DEMAND_SY
     *
     * @return the value of WATER_QUALITY_FC.OX_DEMAND_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getOxDemandSy() {
        return oxDemandSy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.OX_DEMAND_SY
     *
     * @param oxDemandSy the value for WATER_QUALITY_FC.OX_DEMAND_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setOxDemandSy(String oxDemandSy) {
        this.oxDemandSy = oxDemandSy == null ? null : oxDemandSy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.OX_DEMAND_TY
     *
     * @return the value of WATER_QUALITY_FC.OX_DEMAND_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getOxDemandTy() {
        return oxDemandTy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.OX_DEMAND_TY
     *
     * @param oxDemandTy the value for WATER_QUALITY_FC.OX_DEMAND_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setOxDemandTy(String oxDemandTy) {
        this.oxDemandTy = oxDemandTy == null ? null : oxDemandTy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.BO_DEMAND
     *
     * @return the value of WATER_QUALITY_FC.BO_DEMAND
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getBoDemand() {
        return boDemand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.BO_DEMAND
     *
     * @param boDemand the value for WATER_QUALITY_FC.BO_DEMAND
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setBoDemand(Double boDemand) {
        this.boDemand = boDemand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.BO_DEMAND_SY
     *
     * @return the value of WATER_QUALITY_FC.BO_DEMAND_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getBoDemandSy() {
        return boDemandSy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.BO_DEMAND_SY
     *
     * @param boDemandSy the value for WATER_QUALITY_FC.BO_DEMAND_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setBoDemandSy(String boDemandSy) {
        this.boDemandSy = boDemandSy == null ? null : boDemandSy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.BO_DEMAND_TY
     *
     * @return the value of WATER_QUALITY_FC.BO_DEMAND_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getBoDemandTy() {
        return boDemandTy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.BO_DEMAND_TY
     *
     * @param boDemandTy the value for WATER_QUALITY_FC.BO_DEMAND_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setBoDemandTy(String boDemandTy) {
        this.boDemandTy = boDemandTy == null ? null : boDemandTy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.AMMONIA
     *
     * @return the value of WATER_QUALITY_FC.AMMONIA
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getAmmonia() {
        return ammonia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.AMMONIA
     *
     * @param ammonia the value for WATER_QUALITY_FC.AMMONIA
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setAmmonia(Double ammonia) {
        this.ammonia = ammonia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.AMMONIA_SY
     *
     * @return the value of WATER_QUALITY_FC.AMMONIA_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getAmmoniaSy() {
        return ammoniaSy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.AMMONIA_SY
     *
     * @param ammoniaSy the value for WATER_QUALITY_FC.AMMONIA_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setAmmoniaSy(String ammoniaSy) {
        this.ammoniaSy = ammoniaSy == null ? null : ammoniaSy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.AMMONIA_TY
     *
     * @return the value of WATER_QUALITY_FC.AMMONIA_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getAmmoniaTy() {
        return ammoniaTy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.AMMONIA_TY
     *
     * @param ammoniaTy the value for WATER_QUALITY_FC.AMMONIA_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setAmmoniaTy(String ammoniaTy) {
        this.ammoniaTy = ammoniaTy == null ? null : ammoniaTy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.PHOSPHORUS
     *
     * @return the value of WATER_QUALITY_FC.PHOSPHORUS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getPhosphorus() {
        return phosphorus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.PHOSPHORUS
     *
     * @param phosphorus the value for WATER_QUALITY_FC.PHOSPHORUS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setPhosphorus(Double phosphorus) {
        this.phosphorus = phosphorus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.PHOSPHORUS_SY
     *
     * @return the value of WATER_QUALITY_FC.PHOSPHORUS_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getPhosphorusSy() {
        return phosphorusSy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.PHOSPHORUS_SY
     *
     * @param phosphorusSy the value for WATER_QUALITY_FC.PHOSPHORUS_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setPhosphorusSy(String phosphorusSy) {
        this.phosphorusSy = phosphorusSy == null ? null : phosphorusSy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.PHOSPHORUS_TY
     *
     * @return the value of WATER_QUALITY_FC.PHOSPHORUS_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getPhosphorusTy() {
        return phosphorusTy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.PHOSPHORUS_TY
     *
     * @param phosphorusTy the value for WATER_QUALITY_FC.PHOSPHORUS_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setPhosphorusTy(String phosphorusTy) {
        this.phosphorusTy = phosphorusTy == null ? null : phosphorusTy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.NITROGEN
     *
     * @return the value of WATER_QUALITY_FC.NITROGEN
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getNitrogen() {
        return nitrogen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.NITROGEN
     *
     * @param nitrogen the value for WATER_QUALITY_FC.NITROGEN
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setNitrogen(Double nitrogen) {
        this.nitrogen = nitrogen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.NITROGEN_SY
     *
     * @return the value of WATER_QUALITY_FC.NITROGEN_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getNitrogenSy() {
        return nitrogenSy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.NITROGEN_SY
     *
     * @param nitrogenSy the value for WATER_QUALITY_FC.NITROGEN_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setNitrogenSy(String nitrogenSy) {
        this.nitrogenSy = nitrogenSy == null ? null : nitrogenSy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.NITROGEN_TY
     *
     * @return the value of WATER_QUALITY_FC.NITROGEN_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getNitrogenTy() {
        return nitrogenTy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.NITROGEN_TY
     *
     * @param nitrogenTy the value for WATER_QUALITY_FC.NITROGEN_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setNitrogenTy(String nitrogenTy) {
        this.nitrogenTy = nitrogenTy == null ? null : nitrogenTy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.COPPER
     *
     * @return the value of WATER_QUALITY_FC.COPPER
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getCopper() {
        return copper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.COPPER
     *
     * @param copper the value for WATER_QUALITY_FC.COPPER
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setCopper(Double copper) {
        this.copper = copper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.COPPER_SY
     *
     * @return the value of WATER_QUALITY_FC.COPPER_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getCopperSy() {
        return copperSy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.COPPER_SY
     *
     * @param copperSy the value for WATER_QUALITY_FC.COPPER_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setCopperSy(String copperSy) {
        this.copperSy = copperSy == null ? null : copperSy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.COPPER_TY
     *
     * @return the value of WATER_QUALITY_FC.COPPER_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getCopperTy() {
        return copperTy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.COPPER_TY
     *
     * @param copperTy the value for WATER_QUALITY_FC.COPPER_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setCopperTy(String copperTy) {
        this.copperTy = copperTy == null ? null : copperTy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.ZINC
     *
     * @return the value of WATER_QUALITY_FC.ZINC
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getZinc() {
        return zinc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.ZINC
     *
     * @param zinc the value for WATER_QUALITY_FC.ZINC
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setZinc(Double zinc) {
        this.zinc = zinc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.ZINC_SY
     *
     * @return the value of WATER_QUALITY_FC.ZINC_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getZincSy() {
        return zincSy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.ZINC_SY
     *
     * @param zincSy the value for WATER_QUALITY_FC.ZINC_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setZincSy(String zincSy) {
        this.zincSy = zincSy == null ? null : zincSy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.ZINC_TY
     *
     * @return the value of WATER_QUALITY_FC.ZINC_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getZincTy() {
        return zincTy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.ZINC_TY
     *
     * @param zincTy the value for WATER_QUALITY_FC.ZINC_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setZincTy(String zincTy) {
        this.zincTy = zincTy == null ? null : zincTy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.FLUORIDE
     *
     * @return the value of WATER_QUALITY_FC.FLUORIDE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getFluoride() {
        return fluoride;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.FLUORIDE
     *
     * @param fluoride the value for WATER_QUALITY_FC.FLUORIDE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setFluoride(Double fluoride) {
        this.fluoride = fluoride;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.FLUORIDE_SY
     *
     * @return the value of WATER_QUALITY_FC.FLUORIDE_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getFluorideSy() {
        return fluorideSy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.FLUORIDE_SY
     *
     * @param fluorideSy the value for WATER_QUALITY_FC.FLUORIDE_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setFluorideSy(String fluorideSy) {
        this.fluorideSy = fluorideSy == null ? null : fluorideSy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.FLUORIDE_TY
     *
     * @return the value of WATER_QUALITY_FC.FLUORIDE_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getFluorideTy() {
        return fluorideTy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.FLUORIDE_TY
     *
     * @param fluorideTy the value for WATER_QUALITY_FC.FLUORIDE_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setFluorideTy(String fluorideTy) {
        this.fluorideTy = fluorideTy == null ? null : fluorideTy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.SELENIUM
     *
     * @return the value of WATER_QUALITY_FC.SELENIUM
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getSelenium() {
        return selenium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.SELENIUM
     *
     * @param selenium the value for WATER_QUALITY_FC.SELENIUM
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setSelenium(Double selenium) {
        this.selenium = selenium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.SELENIUM_SY
     *
     * @return the value of WATER_QUALITY_FC.SELENIUM_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getSeleniumSy() {
        return seleniumSy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.SELENIUM_SY
     *
     * @param seleniumSy the value for WATER_QUALITY_FC.SELENIUM_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setSeleniumSy(String seleniumSy) {
        this.seleniumSy = seleniumSy == null ? null : seleniumSy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.SELENIUM_TY
     *
     * @return the value of WATER_QUALITY_FC.SELENIUM_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getSeleniumTy() {
        return seleniumTy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.SELENIUM_TY
     *
     * @param seleniumTy the value for WATER_QUALITY_FC.SELENIUM_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setSeleniumTy(String seleniumTy) {
        this.seleniumTy = seleniumTy == null ? null : seleniumTy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.ARSENIC
     *
     * @return the value of WATER_QUALITY_FC.ARSENIC
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getArsenic() {
        return arsenic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.ARSENIC
     *
     * @param arsenic the value for WATER_QUALITY_FC.ARSENIC
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setArsenic(Double arsenic) {
        this.arsenic = arsenic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.ARSENIC_SY
     *
     * @return the value of WATER_QUALITY_FC.ARSENIC_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getArsenicSy() {
        return arsenicSy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.ARSENIC_SY
     *
     * @param arsenicSy the value for WATER_QUALITY_FC.ARSENIC_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setArsenicSy(String arsenicSy) {
        this.arsenicSy = arsenicSy == null ? null : arsenicSy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.ARSENIC_TY
     *
     * @return the value of WATER_QUALITY_FC.ARSENIC_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getArsenicTy() {
        return arsenicTy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.ARSENIC_TY
     *
     * @param arsenicTy the value for WATER_QUALITY_FC.ARSENIC_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setArsenicTy(String arsenicTy) {
        this.arsenicTy = arsenicTy == null ? null : arsenicTy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.MERCURY
     *
     * @return the value of WATER_QUALITY_FC.MERCURY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getMercury() {
        return mercury;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.MERCURY
     *
     * @param mercury the value for WATER_QUALITY_FC.MERCURY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setMercury(Double mercury) {
        this.mercury = mercury;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.MERCURY_SY
     *
     * @return the value of WATER_QUALITY_FC.MERCURY_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getMercurySy() {
        return mercurySy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.MERCURY_SY
     *
     * @param mercurySy the value for WATER_QUALITY_FC.MERCURY_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setMercurySy(String mercurySy) {
        this.mercurySy = mercurySy == null ? null : mercurySy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.MERCURY_TY
     *
     * @return the value of WATER_QUALITY_FC.MERCURY_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getMercuryTy() {
        return mercuryTy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.MERCURY_TY
     *
     * @param mercuryTy the value for WATER_QUALITY_FC.MERCURY_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setMercuryTy(String mercuryTy) {
        this.mercuryTy = mercuryTy == null ? null : mercuryTy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.CADMIUM
     *
     * @return the value of WATER_QUALITY_FC.CADMIUM
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getCadmium() {
        return cadmium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.CADMIUM
     *
     * @param cadmium the value for WATER_QUALITY_FC.CADMIUM
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setCadmium(Double cadmium) {
        this.cadmium = cadmium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.CADMIUM_SY
     *
     * @return the value of WATER_QUALITY_FC.CADMIUM_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getCadmiumSy() {
        return cadmiumSy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.CADMIUM_SY
     *
     * @param cadmiumSy the value for WATER_QUALITY_FC.CADMIUM_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setCadmiumSy(String cadmiumSy) {
        this.cadmiumSy = cadmiumSy == null ? null : cadmiumSy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.CADMIUM_TY
     *
     * @return the value of WATER_QUALITY_FC.CADMIUM_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getCadmiumTy() {
        return cadmiumTy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.CADMIUM_TY
     *
     * @param cadmiumTy the value for WATER_QUALITY_FC.CADMIUM_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setCadmiumTy(String cadmiumTy) {
        this.cadmiumTy = cadmiumTy == null ? null : cadmiumTy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.CHROMIUM
     *
     * @return the value of WATER_QUALITY_FC.CHROMIUM
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getChromium() {
        return chromium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.CHROMIUM
     *
     * @param chromium the value for WATER_QUALITY_FC.CHROMIUM
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setChromium(Double chromium) {
        this.chromium = chromium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.CHROMIUM_SY
     *
     * @return the value of WATER_QUALITY_FC.CHROMIUM_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getChromiumSy() {
        return chromiumSy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.CHROMIUM_SY
     *
     * @param chromiumSy the value for WATER_QUALITY_FC.CHROMIUM_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setChromiumSy(String chromiumSy) {
        this.chromiumSy = chromiumSy == null ? null : chromiumSy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.CHROMIUM_TY
     *
     * @return the value of WATER_QUALITY_FC.CHROMIUM_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getChromiumTy() {
        return chromiumTy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.CHROMIUM_TY
     *
     * @param chromiumTy the value for WATER_QUALITY_FC.CHROMIUM_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setChromiumTy(String chromiumTy) {
        this.chromiumTy = chromiumTy == null ? null : chromiumTy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.LEAD
     *
     * @return the value of WATER_QUALITY_FC.LEAD
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getLead() {
        return lead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.LEAD
     *
     * @param lead the value for WATER_QUALITY_FC.LEAD
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setLead(Double lead) {
        this.lead = lead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.LEAD_SY
     *
     * @return the value of WATER_QUALITY_FC.LEAD_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getLeadSy() {
        return leadSy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.LEAD_SY
     *
     * @param leadSy the value for WATER_QUALITY_FC.LEAD_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setLeadSy(String leadSy) {
        this.leadSy = leadSy == null ? null : leadSy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.LEAD_TY
     *
     * @return the value of WATER_QUALITY_FC.LEAD_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getLeadTy() {
        return leadTy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.LEAD_TY
     *
     * @param leadTy the value for WATER_QUALITY_FC.LEAD_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setLeadTy(String leadTy) {
        this.leadTy = leadTy == null ? null : leadTy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.CYANIDE
     *
     * @return the value of WATER_QUALITY_FC.CYANIDE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getCyanide() {
        return cyanide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.CYANIDE
     *
     * @param cyanide the value for WATER_QUALITY_FC.CYANIDE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setCyanide(Double cyanide) {
        this.cyanide = cyanide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.CYANIDE_SY
     *
     * @return the value of WATER_QUALITY_FC.CYANIDE_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getCyanideSy() {
        return cyanideSy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.CYANIDE_SY
     *
     * @param cyanideSy the value for WATER_QUALITY_FC.CYANIDE_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setCyanideSy(String cyanideSy) {
        this.cyanideSy = cyanideSy == null ? null : cyanideSy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.CYANIDE_TY
     *
     * @return the value of WATER_QUALITY_FC.CYANIDE_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getCyanideTy() {
        return cyanideTy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.CYANIDE_TY
     *
     * @param cyanideTy the value for WATER_QUALITY_FC.CYANIDE_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setCyanideTy(String cyanideTy) {
        this.cyanideTy = cyanideTy == null ? null : cyanideTy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.PHENOL
     *
     * @return the value of WATER_QUALITY_FC.PHENOL
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getPhenol() {
        return phenol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.PHENOL
     *
     * @param phenol the value for WATER_QUALITY_FC.PHENOL
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setPhenol(Double phenol) {
        this.phenol = phenol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.PHENOL_SY
     *
     * @return the value of WATER_QUALITY_FC.PHENOL_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getPhenolSy() {
        return phenolSy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.PHENOL_SY
     *
     * @param phenolSy the value for WATER_QUALITY_FC.PHENOL_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setPhenolSy(String phenolSy) {
        this.phenolSy = phenolSy == null ? null : phenolSy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.PHENOL_TY
     *
     * @return the value of WATER_QUALITY_FC.PHENOL_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getPhenolTy() {
        return phenolTy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.PHENOL_TY
     *
     * @param phenolTy the value for WATER_QUALITY_FC.PHENOL_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setPhenolTy(String phenolTy) {
        this.phenolTy = phenolTy == null ? null : phenolTy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.PETROLEUM
     *
     * @return the value of WATER_QUALITY_FC.PETROLEUM
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getPetroleum() {
        return petroleum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.PETROLEUM
     *
     * @param petroleum the value for WATER_QUALITY_FC.PETROLEUM
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setPetroleum(Double petroleum) {
        this.petroleum = petroleum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.PETROLEUM_SY
     *
     * @return the value of WATER_QUALITY_FC.PETROLEUM_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getPetroleumSy() {
        return petroleumSy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.PETROLEUM_SY
     *
     * @param petroleumSy the value for WATER_QUALITY_FC.PETROLEUM_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setPetroleumSy(String petroleumSy) {
        this.petroleumSy = petroleumSy == null ? null : petroleumSy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.PETROLEUM_TY
     *
     * @return the value of WATER_QUALITY_FC.PETROLEUM_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getPetroleumTy() {
        return petroleumTy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.PETROLEUM_TY
     *
     * @param petroleumTy the value for WATER_QUALITY_FC.PETROLEUM_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setPetroleumTy(String petroleumTy) {
        this.petroleumTy = petroleumTy == null ? null : petroleumTy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.SURFACTANT
     *
     * @return the value of WATER_QUALITY_FC.SURFACTANT
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getSurfactant() {
        return surfactant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.SURFACTANT
     *
     * @param surfactant the value for WATER_QUALITY_FC.SURFACTANT
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setSurfactant(Double surfactant) {
        this.surfactant = surfactant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.SURFACTANT_SY
     *
     * @return the value of WATER_QUALITY_FC.SURFACTANT_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getSurfactantSy() {
        return surfactantSy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.SURFACTANT_SY
     *
     * @param surfactantSy the value for WATER_QUALITY_FC.SURFACTANT_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setSurfactantSy(String surfactantSy) {
        this.surfactantSy = surfactantSy == null ? null : surfactantSy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.SURFACTANT_TY
     *
     * @return the value of WATER_QUALITY_FC.SURFACTANT_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getSurfactantTy() {
        return surfactantTy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.SURFACTANT_TY
     *
     * @param surfactantTy the value for WATER_QUALITY_FC.SURFACTANT_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setSurfactantTy(String surfactantTy) {
        this.surfactantTy = surfactantTy == null ? null : surfactantTy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.SULFIDE
     *
     * @return the value of WATER_QUALITY_FC.SULFIDE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getSulfide() {
        return sulfide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.SULFIDE
     *
     * @param sulfide the value for WATER_QUALITY_FC.SULFIDE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setSulfide(Double sulfide) {
        this.sulfide = sulfide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.SULFIDE_SY
     *
     * @return the value of WATER_QUALITY_FC.SULFIDE_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getSulfideSy() {
        return sulfideSy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.SULFIDE_SY
     *
     * @param sulfideSy the value for WATER_QUALITY_FC.SULFIDE_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setSulfideSy(String sulfideSy) {
        this.sulfideSy = sulfideSy == null ? null : sulfideSy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.SULFIDE_TY
     *
     * @return the value of WATER_QUALITY_FC.SULFIDE_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getSulfideTy() {
        return sulfideTy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.SULFIDE_TY
     *
     * @param sulfideTy the value for WATER_QUALITY_FC.SULFIDE_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setSulfideTy(String sulfideTy) {
        this.sulfideTy = sulfideTy == null ? null : sulfideTy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.COLIFORM
     *
     * @return the value of WATER_QUALITY_FC.COLIFORM
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getColiform() {
        return coliform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.COLIFORM
     *
     * @param coliform the value for WATER_QUALITY_FC.COLIFORM
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setColiform(Double coliform) {
        this.coliform = coliform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.COLIFORM_SY
     *
     * @return the value of WATER_QUALITY_FC.COLIFORM_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getColiformSy() {
        return coliformSy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.COLIFORM_SY
     *
     * @param coliformSy the value for WATER_QUALITY_FC.COLIFORM_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setColiformSy(String coliformSy) {
        this.coliformSy = coliformSy == null ? null : coliformSy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.COLIFORM_TY
     *
     * @return the value of WATER_QUALITY_FC.COLIFORM_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getColiformTy() {
        return coliformTy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.COLIFORM_TY
     *
     * @param coliformTy the value for WATER_QUALITY_FC.COLIFORM_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setColiformTy(String coliformTy) {
        this.coliformTy = coliformTy == null ? null : coliformTy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.CHLOR_A
     *
     * @return the value of WATER_QUALITY_FC.CHLOR_A
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getChlorA() {
        return chlorA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.CHLOR_A
     *
     * @param chlorA the value for WATER_QUALITY_FC.CHLOR_A
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setChlorA(Double chlorA) {
        this.chlorA = chlorA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.CHLOR_A_SY
     *
     * @return the value of WATER_QUALITY_FC.CHLOR_A_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getChlorASy() {
        return chlorASy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.CHLOR_A_SY
     *
     * @param chlorASy the value for WATER_QUALITY_FC.CHLOR_A_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setChlorASy(String chlorASy) {
        this.chlorASy = chlorASy == null ? null : chlorASy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.CHLOR_A_TY
     *
     * @return the value of WATER_QUALITY_FC.CHLOR_A_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getChlorATy() {
        return chlorATy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.CHLOR_A_TY
     *
     * @param chlorATy the value for WATER_QUALITY_FC.CHLOR_A_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setChlorATy(String chlorATy) {
        this.chlorATy = chlorATy == null ? null : chlorATy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.TRANSPARENCY
     *
     * @return the value of WATER_QUALITY_FC.TRANSPARENCY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getTransparency() {
        return transparency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.TRANSPARENCY
     *
     * @param transparency the value for WATER_QUALITY_FC.TRANSPARENCY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setTransparency(Double transparency) {
        this.transparency = transparency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.TRANSPARENCY_SY
     *
     * @return the value of WATER_QUALITY_FC.TRANSPARENCY_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getTransparencySy() {
        return transparencySy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.TRANSPARENCY_SY
     *
     * @param transparencySy the value for WATER_QUALITY_FC.TRANSPARENCY_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setTransparencySy(String transparencySy) {
        this.transparencySy = transparencySy == null ? null : transparencySy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.TRANSPARENCY_TY
     *
     * @return the value of WATER_QUALITY_FC.TRANSPARENCY_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getTransparencyTy() {
        return transparencyTy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.TRANSPARENCY_TY
     *
     * @param transparencyTy the value for WATER_QUALITY_FC.TRANSPARENCY_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setTransparencyTy(String transparencyTy) {
        this.transparencyTy = transparencyTy == null ? null : transparencyTy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.SUSPENDED
     *
     * @return the value of WATER_QUALITY_FC.SUSPENDED
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getSuspended() {
        return suspended;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.SUSPENDED
     *
     * @param suspended the value for WATER_QUALITY_FC.SUSPENDED
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setSuspended(Double suspended) {
        this.suspended = suspended;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.SUSPENDED_SY
     *
     * @return the value of WATER_QUALITY_FC.SUSPENDED_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getSuspendedSy() {
        return suspendedSy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.SUSPENDED_SY
     *
     * @param suspendedSy the value for WATER_QUALITY_FC.SUSPENDED_SY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setSuspendedSy(String suspendedSy) {
        this.suspendedSy = suspendedSy == null ? null : suspendedSy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.SUSPENDED_TY
     *
     * @return the value of WATER_QUALITY_FC.SUSPENDED_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getSuspendedTy() {
        return suspendedTy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.SUSPENDED_TY
     *
     * @param suspendedTy the value for WATER_QUALITY_FC.SUSPENDED_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setSuspendedTy(String suspendedTy) {
        this.suspendedTy = suspendedTy == null ? null : suspendedTy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.QA_TY
     *
     * @return the value of WATER_QUALITY_FC.QA_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getQaTy() {
        return qaTy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.QA_TY
     *
     * @param qaTy the value for WATER_QUALITY_FC.QA_TY
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setQaTy(String qaTy) {
        this.qaTy = qaTy == null ? null : qaTy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.MON_UNIT
     *
     * @return the value of WATER_QUALITY_FC.MON_UNIT
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getMonUnit() {
        return monUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.MON_UNIT
     *
     * @param monUnit the value for WATER_QUALITY_FC.MON_UNIT
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setMonUnit(String monUnit) {
        this.monUnit = monUnit == null ? null : monUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.MONITOR
     *
     * @return the value of WATER_QUALITY_FC.MONITOR
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getMonitor() {
        return monitor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.MONITOR
     *
     * @param monitor the value for WATER_QUALITY_FC.MONITOR
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setMonitor(String monitor) {
        this.monitor = monitor == null ? null : monitor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.INPUTER
     *
     * @return the value of WATER_QUALITY_FC.INPUTER
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getInputer() {
        return inputer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.INPUTER
     *
     * @param inputer the value for WATER_QUALITY_FC.INPUTER
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setInputer(String inputer) {
        this.inputer = inputer == null ? null : inputer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.AUDITOR
     *
     * @return the value of WATER_QUALITY_FC.AUDITOR
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getAuditor() {
        return auditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.AUDITOR
     *
     * @param auditor the value for WATER_QUALITY_FC.AUDITOR
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setAuditor(String auditor) {
        this.auditor = auditor == null ? null : auditor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.CREATE_TIME
     *
     * @return the value of WATER_QUALITY_FC.CREATE_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.CREATE_TIME
     *
     * @param createTime the value for WATER_QUALITY_FC.CREATE_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.MODIFY_TIME
     *
     * @return the value of WATER_QUALITY_FC.MODIFY_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.MODIFY_TIME
     *
     * @param modifyTime the value for WATER_QUALITY_FC.MODIFY_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.REMARKS
     *
     * @return the value of WATER_QUALITY_FC.REMARKS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.REMARKS
     *
     * @param remarks the value for WATER_QUALITY_FC.REMARKS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WATER_QUALITY_FC.REPORT_ID
     *
     * @return the value of WATER_QUALITY_FC.REPORT_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getReportId() {
        return reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WATER_QUALITY_FC.REPORT_ID
     *
     * @param reportId the value for WATER_QUALITY_FC.REPORT_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setReportId(String reportId) {
        this.reportId = reportId == null ? null : reportId.trim();
    }
}