package com.rdc.kingsa.input.persistence.dao;

import com.rdc.kingsa.input.persistence.beans.ApprovalDetail;
import java.util.List;

public interface ApprovalDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPROVAL_DETAIL
     *
     * @mbggenerated Sat Sep 22 20:23:37 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPROVAL_DETAIL
     *
     * @mbggenerated Sat Sep 22 20:23:37 CST 2018
     */
    int insert(ApprovalDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPROVAL_DETAIL
     *
     * @mbggenerated Sat Sep 22 20:23:37 CST 2018
     */
    ApprovalDetail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPROVAL_DETAIL
     *
     * @mbggenerated Sat Sep 22 20:23:37 CST 2018
     */
    List<ApprovalDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPROVAL_DETAIL
     *
     * @mbggenerated Sat Sep 22 20:23:37 CST 2018
     */
    int updateByPrimaryKey(ApprovalDetail record);
}