package com.rdc.kingsa.input.persistence.dao;

import com.rdc.kingsa.input.persistence.beans.ClimateValueRain;
import java.util.List;

public interface ClimateValueRainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLIMATE_VALUE_RAIN
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLIMATE_VALUE_RAIN
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int insert(ClimateValueRain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLIMATE_VALUE_RAIN
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    ClimateValueRain selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLIMATE_VALUE_RAIN
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    List<ClimateValueRain> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLIMATE_VALUE_RAIN
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int updateByPrimaryKey(ClimateValueRain record);
}