package com.rdc.kingsa.input.persistence.dao;

import com.rdc.kingsa.input.persistence.beans.ClimateValueWet;
import java.util.List;

public interface ClimateValueWetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLIMATE_VALUE_WET
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLIMATE_VALUE_WET
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int insert(ClimateValueWet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLIMATE_VALUE_WET
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    ClimateValueWet selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLIMATE_VALUE_WET
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    List<ClimateValueWet> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLIMATE_VALUE_WET
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int updateByPrimaryKey(ClimateValueWet record);
}