package com.rdc.kingsa.input.persistence.dao;

import com.rdc.kingsa.input.persistence.beans.FaultInfo;
import java.util.List;

public interface FaultInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FAULT_INFO
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int insert(FaultInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FAULT_INFO
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    List<FaultInfo> selectAll();
}