package com.rdc.kingsa.input.persistence.dao;

import com.rdc.kingsa.input.persistence.beans.FdaMonitorValWind;
import java.util.List;

public interface FdaMonitorValWindMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FDA_MONITOR_VAL_WIND
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FDA_MONITOR_VAL_WIND
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int insert(FdaMonitorValWind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FDA_MONITOR_VAL_WIND
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    FdaMonitorValWind selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FDA_MONITOR_VAL_WIND
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    List<FdaMonitorValWind> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FDA_MONITOR_VAL_WIND
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int updateByPrimaryKey(FdaMonitorValWind record);
}