package com.rdc.kingsa.input.persistence.dao;

import com.rdc.kingsa.input.persistence.beans.FreshRecord;
import java.util.List;

public interface FreshRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FRESH_RECORD
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FRESH_RECORD
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int insert(FreshRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FRESH_RECORD
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    FreshRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FRESH_RECORD
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    List<FreshRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FRESH_RECORD
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int updateByPrimaryKey(FreshRecord record);
}