package com.rdc.kingsa.input.persistence.dao;

import java.util.List;

import com.base.dal.mybatis.BaseDao;
import com.rdc.kingsa.input.persistence.beans.GssFc;

public interface GssFcMapper extends BaseDao<GssFc, String> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GSS_FC
     *
     * @mbggenerated Sat Sep 29 22:44:50 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GSS_FC
     *
     * @mbggenerated Sat Sep 29 22:44:50 CST 2018
     */
    int insert(GssFc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GSS_FC
     *
     * @mbggenerated Sat Sep 29 22:44:50 CST 2018
     */
    GssFc selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GSS_FC
     *
     * @mbggenerated Sat Sep 29 22:44:50 CST 2018
     */
    List<GssFc> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GSS_FC
     *
     * @mbggenerated Sat Sep 29 22:44:50 CST 2018
     */
    int updateByPrimaryKey(GssFc record);
}