package com.rdc.kingsa.input.persistence.dao;

import com.rdc.kingsa.input.persistence.beans.HeavyMetalEstimate;
import java.util.List;

public interface HeavyMetalEstimateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HEAVY_METAL_ESTIMATE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HEAVY_METAL_ESTIMATE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int insert(HeavyMetalEstimate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HEAVY_METAL_ESTIMATE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    HeavyMetalEstimate selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HEAVY_METAL_ESTIMATE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    List<HeavyMetalEstimate> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HEAVY_METAL_ESTIMATE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int updateByPrimaryKey(HeavyMetalEstimate record);
}