package com.rdc.kingsa.input.persistence.dao;

import com.rdc.kingsa.input.persistence.beans.HydrWaterFlowMonth;
import java.util.List;

public interface HydrWaterFlowMonthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HYDR_WATER_FLOW_MONTH
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HYDR_WATER_FLOW_MONTH
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int insert(HydrWaterFlowMonth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HYDR_WATER_FLOW_MONTH
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    HydrWaterFlowMonth selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HYDR_WATER_FLOW_MONTH
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    List<HydrWaterFlowMonth> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HYDR_WATER_FLOW_MONTH
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int updateByPrimaryKey(HydrWaterFlowMonth record);
}