package com.rdc.kingsa.input.persistence.dao;

import com.rdc.kingsa.input.persistence.beans.MonitoringReport;
import java.util.List;

public interface MonitoringReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MONITORING_REPORT
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MONITORING_REPORT
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int insert(MonitoringReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MONITORING_REPORT
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    MonitoringReport selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MONITORING_REPORT
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    List<MonitoringReport> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MONITORING_REPORT
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int updateByPrimaryKey(MonitoringReport record);
}