package com.rdc.kingsa.input.persistence.dao;

import java.util.List;

import com.base.dal.mybatis.BaseDao;
import com.rdc.kingsa.input.persistence.beans.PhytoplanktonMi;

public interface PhytoplanktonMiMapper extends BaseDao<PhytoplanktonMi, String> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHYTOPLANKTON_MI
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHYTOPLANKTON_MI
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int insert(PhytoplanktonMi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHYTOPLANKTON_MI
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    PhytoplanktonMi selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHYTOPLANKTON_MI
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    List<PhytoplanktonMi> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHYTOPLANKTON_MI
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int updateByPrimaryKey(PhytoplanktonMi record);
}