package com.rdc.kingsa.input.persistence.dao;

import java.util.List;

import com.base.dal.mybatis.BaseDao;
import com.rdc.kingsa.input.persistence.beans.ReproductionEcologyFc;

public interface ReproductionEcologyFcMapper extends BaseDao<ReproductionEcologyFc, String> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPRODUCTION_ECOLOGY_FC
     *
     * @mbggenerated Sat Sep 29 23:14:58 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPRODUCTION_ECOLOGY_FC
     *
     * @mbggenerated Sat Sep 29 23:14:58 CST 2018
     */
    int insert(ReproductionEcologyFc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPRODUCTION_ECOLOGY_FC
     *
     * @mbggenerated Sat Sep 29 23:14:58 CST 2018
     */
    ReproductionEcologyFc selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPRODUCTION_ECOLOGY_FC
     *
     * @mbggenerated Sat Sep 29 23:14:58 CST 2018
     */
    List<ReproductionEcologyFc> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPRODUCTION_ECOLOGY_FC
     *
     * @mbggenerated Sat Sep 29 23:14:58 CST 2018
     */
    int updateByPrimaryKey(ReproductionEcologyFc record);
}