package com.rdc.kingsa.input.persistence.dao;

import com.base.dal.mybatis.BaseDao;
import com.rdc.kingsa.input.persistence.beans.Section;
import com.rdc.kingsa.input.server.controller.model.base.data.SectionMD;

import java.util.List;

public interface SectionMapper extends BaseDao<Section, String> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SECTION
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SECTION
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int insert(Section record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SECTION
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    Section selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SECTION
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    List<Section> selectAll();

    List<SectionMD> selectAllForFront();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SECTION
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int updateByPrimaryKey(Section record);
}