package com.rdc.kingsa.input.persistence.dao;

import com.rdc.kingsa.input.persistence.beans.SecWtm;
import java.util.List;

public interface SecWtmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SEC_WTM
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SEC_WTM
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int insert(SecWtm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SEC_WTM
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    SecWtm selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SEC_WTM
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    List<SecWtm> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SEC_WTM
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int updateByPrimaryKey(SecWtm record);
}