package com.rdc.kingsa.input.persistence.dao;

import com.rdc.kingsa.input.persistence.beans.WaterQualityEstimate;
import java.util.List;

public interface WaterQualityEstimateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WATER_QUALITY_ESTIMATE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WATER_QUALITY_ESTIMATE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int insert(WaterQualityEstimate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WATER_QUALITY_ESTIMATE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    WaterQualityEstimate selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WATER_QUALITY_ESTIMATE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    List<WaterQualityEstimate> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WATER_QUALITY_ESTIMATE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int updateByPrimaryKey(WaterQualityEstimate record);
}