package com.rdc.kingsa.input.persistence.dao;

import com.rdc.kingsa.input.persistence.beans.WaterQualityMi;
import java.util.List;

public interface WaterQualityMiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WATER_QUALITY_MI
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WATER_QUALITY_MI
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int insert(WaterQualityMi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WATER_QUALITY_MI
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    WaterQualityMi selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WATER_QUALITY_MI
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    List<WaterQualityMi> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WATER_QUALITY_MI
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int updateByPrimaryKey(WaterQualityMi record);
}