package com.rdc.kingsa.input.persistence.dao;

import com.rdc.kingsa.input.persistence.beans.ZoobenthosFc;
import java.util.List;

public interface ZoobenthosFcMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZOOBENTHOS_FC
     *
     * @mbggenerated Sat Sep 29 23:18:49 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZOOBENTHOS_FC
     *
     * @mbggenerated Sat Sep 29 23:18:49 CST 2018
     */
    int insert(ZoobenthosFc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZOOBENTHOS_FC
     *
     * @mbggenerated Sat Sep 29 23:18:49 CST 2018
     */
    ZoobenthosFc selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZOOBENTHOS_FC
     *
     * @mbggenerated Sat Sep 29 23:18:49 CST 2018
     */
    List<ZoobenthosFc> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZOOBENTHOS_FC
     *
     * @mbggenerated Sat Sep 29 23:18:49 CST 2018
     */
    int updateByPrimaryKey(ZoobenthosFc record);
}