package com.rdc.kingsa.input.persistence.dao;

import java.util.List;

import com.base.dal.mybatis.BaseDao;
import com.rdc.kingsa.input.persistence.beans.ZoobenthosMi;

public interface ZoobenthosMiMapper extends BaseDao<ZoobenthosMi, String> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZOOBENTHOS_MI
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZOOBENTHOS_MI
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int insert(ZoobenthosMi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZOOBENTHOS_MI
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    ZoobenthosMi selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZOOBENTHOS_MI
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    List<ZoobenthosMi> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZOOBENTHOS_MI
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int updateByPrimaryKey(ZoobenthosMi record);
}