package com.rdc.kingsa.input.persistence.dao;

import java.util.List;

import com.base.dal.mybatis.BaseDao;
import com.rdc.kingsa.input.persistence.beans.ZooplanktonMi;

public interface ZooplanktonMiMapper extends BaseDao<ZooplanktonMi, String> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZOOPLANKTON_MI
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZOOPLANKTON_MI
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int insert(ZooplanktonMi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZOOPLANKTON_MI
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    ZooplanktonMi selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZOOPLANKTON_MI
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    List<ZooplanktonMi> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZOOPLANKTON_MI
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    int updateByPrimaryKey(ZooplanktonMi record);
}