package com.rdc.kingsa.input.server.controller.model;

import com.rdc.kingsa.input.server.controller.model.base.AbstractMD;

import java.util.Date;

public class SecGsmMD extends AbstractMD {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEC_GSM.ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEC_GSM.SECTION_ID
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String sectionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEC_GSM.SERIAL_NUM
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Short serialNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEC_GSM.REGION
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String region;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEC_GSM.SAMP_TYPE
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String sampType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEC_GSM.MONITOR_FREQ
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String monitorFreq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEC_GSM.FROM_XLD
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Double fromXld;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEC_GSM.CREATE_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEC_GSM.MODIFY_TIME
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEC_GSM.REMARKS
     *
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEC_GSM.ID
     *
     * @return the value of SEC_GSM.ID
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEC_GSM.ID
     *
     * @param id the value for SEC_GSM.ID
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEC_GSM.SECTION_ID
     *
     * @return the value of SEC_GSM.SECTION_ID
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getSectionId() {
        return sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEC_GSM.SECTION_ID
     *
     * @param sectionId the value for SEC_GSM.SECTION_ID
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setSectionId(String sectionId) {
        this.sectionId = sectionId == null ? null : sectionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEC_GSM.SERIAL_NUM
     *
     * @return the value of SEC_GSM.SERIAL_NUM
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Short getSerialNum() {
        return serialNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEC_GSM.SERIAL_NUM
     *
     * @param serialNum the value for SEC_GSM.SERIAL_NUM
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setSerialNum(Short serialNum) {
        this.serialNum = serialNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEC_GSM.REGION
     *
     * @return the value of SEC_GSM.REGION
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEC_GSM.REGION
     *
     * @param region the value for SEC_GSM.REGION
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEC_GSM.SAMP_TYPE
     *
     * @return the value of SEC_GSM.SAMP_TYPE
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getSampType() {
        return sampType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEC_GSM.SAMP_TYPE
     *
     * @param sampType the value for SEC_GSM.SAMP_TYPE
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setSampType(String sampType) {
        this.sampType = sampType == null ? null : sampType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEC_GSM.MONITOR_FREQ
     *
     * @return the value of SEC_GSM.MONITOR_FREQ
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getMonitorFreq() {
        return monitorFreq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEC_GSM.MONITOR_FREQ
     *
     * @param monitorFreq the value for SEC_GSM.MONITOR_FREQ
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setMonitorFreq(String monitorFreq) {
        this.monitorFreq = monitorFreq == null ? null : monitorFreq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEC_GSM.FROM_XLD
     *
     * @return the value of SEC_GSM.FROM_XLD
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Double getFromXld() {
        return fromXld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEC_GSM.FROM_XLD
     *
     * @param fromXld the value for SEC_GSM.FROM_XLD
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setFromXld(Double fromXld) {
        this.fromXld = fromXld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEC_GSM.CREATE_TIME
     *
     * @return the value of SEC_GSM.CREATE_TIME
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEC_GSM.CREATE_TIME
     *
     * @param createTime the value for SEC_GSM.CREATE_TIME
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEC_GSM.MODIFY_TIME
     *
     * @return the value of SEC_GSM.MODIFY_TIME
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEC_GSM.MODIFY_TIME
     *
     * @param modifyTime the value for SEC_GSM.MODIFY_TIME
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEC_GSM.REMARKS
     *
     * @return the value of SEC_GSM.REMARKS
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEC_GSM.REMARKS
     *
     * @param remarks the value for SEC_GSM.REMARKS
     * @mbggenerated Wed Sep 19 22:37:10 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}